evergreen-ci/ui

git-merge.sh

[DEVPROD-5136](https://jira.mongodb.org/browse/DEVPROD-5136)
Add merge script to combine Spruce and Parsley histories. The contents of each repo will be placed in `apps/spruce` and `apps/parsley`, respectively
I tested this a lot in the [ui-sandbox repo](https://github.com/evergreen-ci/ui-sandbox) and it works great.

DEVPROD-5136: Add merge script

---

apps/parsley/scripts/deploy/email.sh
apps/parsley/scripts/deploy/utils/git/index.ts
apps/spruce/scripts/deploy/email.sh
apps/spruce/scripts/deploy/utils/git/index.ts

DEVPROD-5136
Append `-- .` to `git log` commands used to populate deploy script and email. This should result in only the commits with changes in the current directory (i.e. Spruce or Parsley respectively) being logged.
Tested locally

DEVPROD-5136: Only log commits in current directory for deploy

---

apps/spruce/src/gql/queries/repo-event-logs.graphql
apps/spruce/src/gql/queries/repo-settings.graphql

DEVPROD-5460
Small PR to remove `id` argument from repo queries, since the directive should now be applied to the new `repoId` argument.
* evergreen-ci/evergreen/pull/7702

DEVPROD-5460: Remove id argument from repo queries

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/CodeChanges/index.tsx
apps/spruce/src/gql/generated/types.ts

DEVPROD-5879
Updates the "No code changes" text to handle a case with diff too large to display 
https://jira.mongodb.org/browse/DEVPROD-5926
This is a quick fix until we differentiate no code change and too many code change

DEVPROD-5879 Update no code change text

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/spawn/host.ts
apps/spruce/src/components/ProjectSelect/__snapshots__/ProjectSelect.stories.storyshot
apps/spruce/src/components/SearchableDropdown/__snapshots__/SearchableDropdown.stories.storyshot
apps/spruce/src/components/SearchableDropdown/index.tsx
apps/spruce/src/components/Spawn/getFormSchema.tsx
apps/spruce/src/components/Spawn/index.tsx
apps/spruce/src/components/Spawn/spawnHostModal/getFormSchema.tsx
apps/spruce/src/components/Spawn/spawnHostModal/transformer.test.ts
apps/spruce/src/components/Spawn/spawnHostModal/transformer.ts
apps/spruce/src/components/Spawn/spawnHostModal/types.ts
apps/spruce/src/components/Spawn/utils.ts
apps/spruce/src/components/SpruceForm/FieldTemplates/ObjectFieldTemplates/index.tsx
apps/spruce/src/components/SpruceForm/FieldTemplates/index.tsx
apps/spruce/src/components/SpruceForm/Widgets/DateTimePicker.tsx
apps/spruce/src/components/SpruceForm/Widgets/DayPicker.tsx
apps/spruce/src/components/SpruceForm/Widgets/index.tsx
apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot
apps/spruce/src/constants/fieldMaps.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/spawn/spawnHost/spawnHostButton/SpawnHostModal.tsx
apps/spruce/src/pages/spawn/spawnVolume/spawnVolumeTableActions/MigrateVolumeModal.tsx

DEVPROD-4197
- For **non-production** environments, allow users to configure an uptime schedule when spawning a host
- This PR is not feature complete for the product, but I wanted to put something up for @Kimchelly to use in staging/beta before I leave for vacation.
- I'll implement this on the edit modal in a new PR.
- Reorganize spawn host modal slightly according to Will's designs
- Add validation preventing users from saving if they don't have at least 24 hours of sleep time/week. A warning is showed if they have less than 48 hours of sleep time (but they can still save). The messaging text is dependent on whether the user is running for continuous days or sleeping at night.
> <img width="573" alt="image" src="https://github.com/evergreen-ci/ui/assets/9298431/40870cab-53d6-495e-9991-6 …

DEVPROD-4197: Add host uptime scheduler

---

apps/spruce/cypress/integration/projectSettings/admin_actions.ts

DEVPROD-5953
Since I'm updating the directives, the error message changed; I think it's just easier to remove the check.

DEVPROD-5953: Remove validation for error message in admin_actions.ts

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mocks/getSpruceConfig.ts
apps/spruce/src/gql/queries/distro.graphql
apps/spruce/src/gql/queries/spruce-config.graphql
apps/spruce/src/pages/distroSettings/tabs/HostTab/HostTab.tsx
apps/spruce/src/pages/distroSettings/tabs/HostTab/getFormSchema.tsx
apps/spruce/src/pages/distroSettings/tabs/HostTab/schemaFields.tsx
apps/spruce/src/pages/distroSettings/tabs/HostTab/transformers.test.ts
apps/spruce/src/pages/distroSettings/tabs/HostTab/transformers.ts
apps/spruce/src/pages/distroSettings/tabs/HostTab/types.ts
apps/spruce/src/pages/distroSettings/tabs/testData.ts

[DEVPROD-4798](https://jira.mongodb.org/browse/DEVPROD-4798)
https://github.com/evergreen-ci/evergreen/pull/7713 removes the ssh key field from distros and also from the admin config. This PR will remove it from Spruce as well.
I'm not 100% sure how to coordinate the merging/deploys of these. Does the Spruce change go first and then the Evergreen one? But wouldn't a distro update break without the mandatory ssh key field? But if Evergreen goes first it won't be providing the required field. 😕 
Seems to still work locally.
https://github.com/evergreen-ci/evergreen/pull/7713

DEVPROD-4798 remove ssh keys from distro host settings

---

apps/spruce/cypress/integration/version/task_table.ts

DEVPROD-597
I think these tests should be deleted (and I was going to delete them anyways in [DEVPROD-5935](https://jira.mongodb.org/browse/DEVPROD-5935)). They have been skipped for more than 3 years now; it's unlikely that they have a large impact else we would have fixed them by now. Additionally, the functions `assertCorrectRequestVariables` and `clickSorterAndAssertTasksAreFetched` appear to have been erased from the codebase.

DEVPROD-597: Delete unused tests in task_table.ts

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/gql/generated/types.ts

[DEVPROD-4798](https://jira.mongodb.org/browse/DEVPROD-4798)
Should be the last PR for this ticket. These fields were removed by https://github.com/evergreen-ci/evergreen/pull/7713.
This PR is a `yarn codegen` to keep them in sync.
local-evergreen/yarn dev works
https://github.com/evergreen-ci/evergreen/pull/7713

DEVPROD-4798 remove sshKey/keys fields

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/task.graphql
apps/spruce/src/gql/queries/version-task-durations.graphql

DEVPROD-4730
Rendering the variant history link requires knowing the projectIdentifier for tasks 
The link now works

DEVPROD-4730 Add projectIdentifier field to TaskQuery for Execution tasks table

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/job_logs.ts
apps/spruce/cypress/integration/projectHealth/task_history.ts
apps/spruce/cypress/integration/projectHealth/variant_history.ts
apps/spruce/src/gql/generated/types.ts

DEVPROD-5953
Due to adding directives on the underlying queries, the error message received from the backend has changed. I just removed them so we don't have to do this again if it changes in the future.

DEVPROD-5953: Update Cypress tests that fail due to directives

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/PatchActionButtons/DisableTasks.tsx
apps/spruce/src/components/PatchActionButtons/ScheduleUndispatchedBaseTasks.tsx
apps/spruce/src/components/PatchActionButtons/UnscheduleTasks.tsx
apps/spruce/src/components/PatchesPage/PatchCard/DropdownMenu.tsx
apps/spruce/src/components/SetPriority/SetPriority.test.tsx
apps/spruce/src/components/SetPriority/index.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mutations/index.ts
apps/spruce/src/gql/mutations/schedule-undispatched-base-tasks.graphql
apps/spruce/src/gql/mutations/set-patch-priority.graphql
apps/spruce/src/gql/mutations/set-version-priority.graphql
apps/spruce/src/gql/mutations/unschedule-patch-tasks.graphql
apps/spruce/src/gql/mutations/unschedule-version-tasks.graphql
apps/spruce/src/pages/version/ActionButtons.tsx

DEVPROD-6691
Just replaces old patch mutations with new version mutations. Cleaned up some usage of `versionId` vs `patchId`.
* Against staging & production
* These mutations already have directives applied, so confirmed that I can set priority / unschedule mainline commits and patches.
* [Patch with module](https://spruce.mongodb.com/version/6626bef09ed761000764a714/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
* evergreen-ci/evergreen/pull/7778

DEVPROD-6691: Replace deprecated patch mutations with equivalent version mutations

---

apps/parsley/scripts/deploy/utils/deploy/index.ts
apps/parsley/scripts/deploy/utils/git/index.ts
apps/spruce/scripts/deploy/utils/deploy/index.ts
apps/spruce/scripts/deploy/utils/git/index.ts

DEVPROD-5137
Bynn saw this error when attempting to deploy:
```zsh
❯ yarn deploy:prod
yarn run v1.22.21
$ env-cmd -e production ts-node scripts/deploy/run-deploy
Checking if you are on the main branch
Currently Deployed Commit: 559f14a10b756c6e40f034e18b30756efd318eb7
/bin/sh: line 1: /apps/spruce: No such file or directory
/bin/sh: line 2: /packages: No such file or directory
Error: Command failed: git log 559f14a10b756c6e40f034e18b30756efd318eb7..HEAD --oneline -- /Users/bynn.lee/go/src/github.com/evergreen-ci/ui
/apps/spruce -- /Users/bynn.lee/go/src/github.com/evergreen-ci/ui
/packages
```
I forgot to trim the strings returned by `execSync`, which we do elsewhere, resulting in an extraneous newline. This meant that the paths created by `paths.resolve()` were invalid.
- Tested locally

DEVPROD-5137 fix: Trim execsync strings

---

apps/parsley/package.json
apps/spruce/package.json
packages/eslint-config-evg/package.json
yarn.lock

DEVPROD-2938
Just a straightforward upgrade for `@typescript-eslint/parser`, `@typescript-eslint/eslint-plugin`, and `eslint`. 
This package [has support for ESLint flat config](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/#switching-to-typescript-eslint) but given that we don't have flat config yet, I did not use it.
- Checked that ESLint and TypeScript errors still work on VSCode

DEVPROD-2938: Upgrade @typescript-eslint/parser and @typescript-eslint/eslint-plugin to v7.8.0

---

apps/spruce/src/components/Banners/GithubUsernameBanner.tsx

DEVPROD-4779 Show GitHub username banner on all pages

---

scripts/evg-db-ops.sh

DEVPROD-2985
Add `--quiet` to `mongodump` invocation. The `mongorestore` call already includes it.
This doesn't really make a difference in the log length because the evergreen server is still pretty noisy around these operations, but oh well 🤷‍♀️

DEVPROD-2985: Quiet mongodump

---

apps/spruce/src/hooks/useBreakingTask/index.ts
apps/spruce/src/hooks/useBreakingTask/useBreakingTask.test.tsx
apps/spruce/src/hooks/useLastExecutedTask/index.ts
apps/spruce/src/hooks/useLastExecutedTask/useLastExecutedTask.test.tsx
apps/spruce/src/hooks/useLastPassingTask/index.ts
apps/spruce/src/hooks/useLastPassingTask/useLastPassingTask.test.tsx

DEVPROD-4265
I think we should just remove these toasts. It's confusing to discern their origin because they're hidden within the previous commits selector. 
The options in the previous commits selector will be disabled is there's no commit to navigate to, and I think that is enough of a signal for now.
It's also the cause of many other problem tickets:
* [DEVPROD-3492](https://jira.mongodb.org/browse/DEVPROD-3492)
* [DEVPROD-5909](https://jira.mongodb.org/browse/DEVPROD-5909)
* Updated tests

DEVPROD-4265: Remove error toasts for relevant commits

---

apps/spruce/cypress/integration/myPatches/my_patches.ts
apps/spruce/src/components/PatchesPage/index.tsx

DEVPROD-795
Adds regex validation on the patches page search input

DEVPROD-795 Fix search input validation on PatchesPage

---

apps/spruce/cypress/integration/container/container_events.ts
apps/spruce/src/pages/container/EventsTable/EventCopy.tsx
apps/spruce/src/pages/container/EventsTable/index.tsx

DEVPROD-6782
Stop using V11 adapter for this table. Note that V11 adapter cannot be removed from the codebase because it is still being used for the EventDiff table.
* Update Cypress test

DEVPROD-6782: Update container events table

---

apps/spruce/cypress/integration/projectSettings/access.ts
apps/spruce/cypress/integration/projectSettings/defaulting_to_repo.ts
apps/spruce/cypress/integration/projectSettings/repo_settings.ts
apps/spruce/src/constants/externalResources.ts
apps/spruce/src/pages/projectSettings/DefaultSectionToRepoModal.tsx
apps/spruce/src/pages/projectSettings/HeaderButtons.tsx

DEVPROD-4757
This PR adds an additional layer of confirmation with some additional information so users know that the default to repo action is not reversible. 
e2e tests

DEVPROD-4757 Add additional confirmation to default to repo button

---

apps/spruce/src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx
apps/spruce/src/pages/projectSettings/tabs/PluginsTab/getFormSchema.tsx

DEVPROD-4665 
Disables the ability to toggle performance plugin settings when looking at a repo

DEVPROD-4665 Disable performance plugin selection at repo level

---

apps/parsley/cypress/integration/ansiLogs/ansi_logView.ts
apps/spruce/src/constants/externalResources.ts
apps/spruce/src/constants/patch.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/version.graphql
apps/spruce/src/pages/version/Metadata.tsx

DEVPROD-4268
After speaking to Brian, we can't always link to the base commit for certain patches in the GitHub merge queue. In these cases, we should remove the hyperlink.
Geoff also requested a link to the project's merge queue on GitHub. I showed Geoff the changes and he said they would work for him.
(Should I add an external link icon through `hideExternalIcon`?)
* Test using `yarn prod`

DEVPROD-4268: Add link to GitHub merge queue in patch metadata

---

apps/spruce/cypress/integration/distroSettings/navigation.ts
apps/spruce/src/components/styles/SideNav.tsx
apps/spruce/src/pages/distroSettings/index.tsx

DEVPROD-4724
Adds a link to the task queue page from distro settings. cc @minnakt if this location makes sense I based it off of your designs [here](https://www.figma.com/file/f3EEf8eDYgh6tsC9Owkg2M/Image-Visibility-Page?type=design&node-id=465-8844&mode=design&t=zxsD00aysRgAJeOv-0).

DEVPROD-4724 Add link to task queue page from distro settings

---

apps/spruce/src/components/VersionRestartModal/VersionRestartModal.tsx
apps/spruce/src/components/VersionRestartModal/VersionTasks.tsx

DEVPROD-3606
Adds a scrollable container to the restart modal

DEVPROD-3606 Add a scrollable container to version restart modal

---

apps/spruce/src/components/Settings/EventLog/EventDiffTable.tsx
apps/spruce/src/components/Table/BaseTable.tsx
apps/spruce/src/components/Table/__snapshots__/BaseTable.stories.storyshot
apps/spruce/src/pages/task/taskTabs/FileTable/GroupedFileTable/__snapshots__/GroupedFileTable.stories.storyshot
apps/spruce/src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable.stories.storyshot
apps/spruce/src/pages/taskQueue/TaskQueueTable/__snapshots__/TaskQueueTable.stories.storyshot
apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable.stories.storyshot

DEVPROD-7025
Just one last quick win to remove V11 adapter from the event diff table. I believe this means we no longer have any usage of V11 adapter.
A nice side effect of this is that things will no longer be cut-off in project & distro events logs:
Before:
After:

DEVPROD-7025: Update event diff table

---

apps/parsley/src/components/BookmarksBar/__snapshots__/BookmarksBar.stories.storyshot
apps/parsley/src/components/BookmarksBar/index.tsx
apps/parsley/src/components/ErrorHandling/Sentry.tsx
apps/parsley/src/components/ErrorHandling/initialize.test.ts
apps/parsley/src/components/ErrorHandling/utils.test.ts
apps/parsley/src/components/ErrorHandling/utils.ts
apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/ErrorHandling/Sentry.tsx
apps/spruce/src/components/ErrorHandling/initialize.test.ts
apps/spruce/src/components/ErrorHandling/utils.test.ts
apps/spruce/src/components/ErrorHandling/utils.ts
apps/spruce/src/gql/generated/types.ts

DEVPROD-3188
This PR overwrites the breadcrumb message for `ui.click` events if a data-cy attribute is available. Otherwise, the breadcrumb message remains the same.
It also adds additional data to the breadcrumb.
Sometimes this doesn't work that well, and that could be because:
* We don't have a data-cy or any other helpful attributes on the element. We would have to go through and manually add them where missing.
* It is somewhat out of our control. For example, Sentry will pick up on this [hidden div](https://github.com/mongodb/leafygreen-ui/blob/a149857b2bd05dbae003f89ba2a8ba449ff7b213/packages/button/src/ButtonContent/ButtonContent.tsx#L93) that LeafyGreen has on its buttons and not the button itself. I feel like the solution for this would be for LeafyGreen to remove hidden divs. …

DEVPROD-3188: Attach additional data to ui.click breadcrumbs in Sentry

---

apps/spruce/src/components/Spawn/utils/hostUptime.ts

DEVPROD-7541
The validator was being too aggressive in applying host uptime rules to production hosts. Remove this check so that the edit spawn host modal is saveable.
- Tested locally

DEVPROD-7541: Don't validate host sleep schedule in prod

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/Spawn/getFormSchema.tsx
apps/spruce/src/components/Spawn/spawnHostModal/transformer.test.ts
apps/spruce/src/components/Spawn/utils/hostUptime.test.ts
apps/spruce/src/components/Spawn/utils/hostUptime.ts
apps/spruce/src/components/SpruceForm/Widgets/DateTimePicker.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/my-hosts.graphql
apps/spruce/src/pages/spawn/spawnHost/PauseSleepScheduleModal.tsx
apps/spruce/src/pages/spawn/spawnHost/SpawnHostTableActions.test.tsx

DEVPROD-7766
- The antd timepicker has a [bug](https://github.com/ant-design/ant-design/issues/45564) that resets the date when the input is typed rather than selected. Disabling typing is the easiest way to get around this (and imo that UX is subpar anyway)
- Use the value for `nextStartDate` from the backend rather than calculating it on the client
- Fix some type errors introduced by `use strict` and app PR
- Validated that datepicker can't have input typed anymore
https://github.com/evergreen-ci/evergreen/pull/7950

DEVPROD-7766: Fix timepicker bug, use nextStartTime from app

---

apps/parsley/src/components/DetailsMenu/DetailsMenuCard/Toggles/PrettyPrintToggle/PrettyPrintToggle.test.tsx
apps/parsley/src/components/LogPane/LogPane.test.tsx
apps/parsley/src/components/LogPane/index.tsx
apps/parsley/src/context/LogContext/index.tsx

DEVPROD-5058
There is a problem where the virtualization library can't compute correct heights without loading initially. This PR makes it so that pretty print is evaluated once the log pane loads. Note that we already do this for the wrap setting. 
* Tested the log in the ticket on Parsley beta

DEVPROD-5058: Apply pretty print setting after log pane has loaded

---

apps/spruce/src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx

DEVPROD-8219 
Tweak description text to include --alias flag.

DEVPROD-8219 add --alias flag to manual patch testing description

---

apps/parsley/src/App.tsx
apps/spruce/src/App.tsx
apps/spruce/src/components/styles/Layout.tsx
apps/spruce/src/pages/404/NotFound.stories.tsx
apps/spruce/src/pages/404/NotFound.tsx
apps/spruce/src/pages/404/NotFoundSvg.tsx
apps/spruce/src/pages/404/__snapshots__/NotFound_Default404.storyshot
apps/spruce/src/utils/environmentVariables.ts
apps/spruce/src/utils/request.ts

DEVPROD-7675
Stop exposing the login route on non-development (staging, beta, production) builds. Also fixed an issue with the 404 image where it wasn't showing up at all.
* On staging, checked that `/login` route 404s
* Also checked that it prompted me to log in in incognito tab 
* On local development, checked that `/login` route is functional

DEVPROD-7675: Avoid exposing /login route in non-development builds

---

apps/spruce/src/pages/projectSettings/getTabTitle.ts
apps/spruce/src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx

DEVPROD-5859 Remove commit queue language
This is a fixup for
https://github.com/evergreen-ci/ui/commit/2e3181a084845839809a38ec44f1e0856cd1159f,
which removes commit queue fields from the project admin UI.

DEVPROD-5859 Remove commit queue language

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/gql/fragments/projectSettings/patchAliases.graphql
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/projectSettings/tabs/PatchAliasesTab/transformers.test.ts
apps/spruce/src/pages/projectSettings/tabs/PatchAliasesTab/transformers.ts
apps/spruce/src/pages/projectSettings/tabs/PatchAliasesTab/types.ts

DEVPROD-7529
Add new `downstreamRevision` field to the UI so that when saving patch trigger aliases in project settings, the field doesn't get cleared. Not implementing a UI component for this field because it's going to be API-only to start, per the linked Evergreen PR.
Tested locally
https://github.com/evergreen-ci/evergreen/pull/8012

DEVPROD-7529 Include downstreamRevision in save project settings mutation

---

apps/spruce/src/pages/projectSettings/CreateDuplicateProjectButton.tsx

DEVPROD-7838
Fix 422 query error that originates from the Duplicate button.
* Before change, you can consistently see a single 422 failed request in the network tab. After change, there is no failed request in the network tab.

DEVPROD-7838: Fix 422 error in CreateDuplicateProjectButton

---

apps/parsley/src/utils/streams/index.ts
apps/parsley/src/utils/streams/streams.test.ts

DEVPROD-4046
The current approach to trimming lines failed to catch any long lines split over multiple chunks. When concatenating the first line with the previously processed line, check whether their combined length is too long and trim if so.
- Add unit test that fails without code changes
- Log linked in ticket now shows warning toast and trims correctly

DEVPROD-4046: Trim lines split between chunks

---

apps/parsley/src/components/PaginatedVirtualList/index.tsx
apps/parsley/src/components/Search/SearchBar/__snapshots__/SearchBar_Default.storyshot
apps/parsley/src/components/Search/SearchBar/__snapshots__/SearchBar_WithSearchSuggestions.storyshot
apps/parsley/src/components/Search/SearchBar/index.tsx
apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/TupleSelect/__snapshots__/TupleSelect_Default.storyshot
apps/spruce/src/components/TupleSelect/index.tsx
apps/spruce/src/components/TupleSelectWithRegexConditional/__snapshots__/TupleSelectWithRegexConditional_WithConditional.storyshot
apps/spruce/src/gql/generated/types.ts

DEVPROD-8143
The most recent upgrade to TextInput resulted in an error message underneath the text-input which pushed content, removed the error icon and adjusted which elements in the dom controlled styles. These code changes remove the error message copy, add in the error icon and adjust the text-input border when it's next a select component.

DEVPROD-8143: Prevent searchbar error from pushing content 

---

apps/spruce/src/gql/client/cache.ts
apps/spruce/src/pages/Version.tsx

DEVPROD-8159
In-app navigation to the version page from a version page results in the Version Metadata panel processing an undefined version object. Resetting the version page state when the versionID URL field changes properly gates page rendering until new data is fetched. 
I'm unable to edit the diagram but this case is basically captured by the diagram entry statement "User Visits /version/{id}".
You can recreate this issue by clicking Previous Commit on this [page](https://spruce.mongodb.com/version/mongodb_mongo_v5.0_809167cbc5a70e1418d8090a7bb6a44395163c7a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

DEVPROD-8159: Prevent Version Metadata Panel from accessing undefined

---

.gitignore
apps/spruce/src/components/Content/index.tsx
apps/spruce/src/constants/routes.ts
apps/spruce/src/pages/Image.tsx
apps/spruce/src/pages/image/index.tsx

DEVPROD-7652
Created new route for image pages at /image/imageID/:tab with tabs of build-information and events.

DEVPROD-7652: Create new route for image pages

---

apps/parsley/src/gql/generated/types.ts
apps/parsley/src/hooks/useTaskQuery/index.ts
apps/spruce/src/analytics/task/useTaskAnalytics.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/Task.tsx

DEVPROD-6860
Allow Task page rendering and populating task analytics metadata even if `task.Annotations` is unavailable due to a permission error. The [SuspectedIssues](https://github.com/evergreen-ci/ui/blob/afd1d715aa6f89e8f3a8f5efecb1678c8bc3ca18/apps/spruce/src/pages/task/taskTabs/buildBaronAndAnnotations/Issues/Issues.tsx#L43), [BuildBaronContent](https://github.com/evergreen-ci/spruce/blob/b3372e60a8e06456701c0d906fe483647b07504b/src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaronContent.tsx#L64), and [Issues](https://github.com/evergreen-ci/ui/blob/afd1d715aa6f89e8f3a8f5efecb1678c8bc3ca18/apps/spruce/src/pages/task/taskTabs/buildBaronAndAnnotations/Issues/Issues.tsx#L43) components all handle empty data.

DEVPROD-6860: Return data alongside errors for some Task GQL queries

---

apps/parsley/src/gql/generated/types.ts
packages/deploy-utils/src/utils/git/get-current-deployed-commit.test.ts
packages/deploy-utils/src/utils/git/get-current-deployed-commit.ts
packages/deploy-utils/src/utils/git/git.test.ts
packages/deploy-utils/src/utils/git/tag.test.ts
packages/deploy-utils/src/utils/git/tag.ts

DEVPROD-5141 - Fix bug introduced in #210 blocking new deploy script from working
- Fix string check: commit fetched from remote file was not being trimmed and so was not 40 characters
- Also validate tag correctly if local commit is used, since it would not be 40 characters
- Add unit tests

DEVPROD-5141: Fix commit check for prod deploy

---

packages/deploy-utils/src/build-and-push/build-and-push.test.ts
packages/deploy-utils/src/build-and-push/index.ts

Fix for DEVPROD-5141
- Write commit.txt file on staging/beta/prod deploys. I opted to include it on non-production since this makes it more testable and keeps the workflows more similar.
- Just deployed to beta at https://spruce-beta.corp.mongodb.com/commit.txt
- This will fix (at least some of) the broken waterfall tests. Tests that look for these files to be deployed are still currently broken.

DEVPROD-5141: Write commit.txt file on deploy

---

apps/parsley/src/utils/logRow/logRow.test.ts

DEVPROD-5295
This fixes a type error introduced in [this](https://spruce.mongodb.com/version/evergreen_ui_db3e6af4878b518493a472b2a67886b82be56cd0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) mainline commit

DEVPROD-5295: Fix type error

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/preferences/preferencesTabs/notificationTab/UserSubscriptions.tsx

DEVPROD-7910
On the notifications page, making any change while not having any individual subscriptions would cause the page to become unresponsive. This was a result of the internal Tanstack table within the subscriptions table attempting to perform operations while empty. The easiest way to get around this is just to split out the table into a separate component that is not rendered if the user has no subscriptions. 
Editing the page with no subscriptions is successful

DEVPROD-7910: Fix unresponsive notifications page bug

---

packages/deploy-utils/src/email/email.test.ts
packages/deploy-utils/src/email/utils.ts

DEVPROD-7027
- Fix mistake where wrong path to command was returned when searching for the Evergreen executable. This led to failures sending today's deploy email ([Parsley](https://spruce.mongodb.com/task/evergreen_ui_parsley_deploy_parsley_prod__parsley_v2.1.34_24_07_15_18_07_14?execution=0), [Spruce](https://spruce.mongodb.com/version/evergreen_ui_spruce_v4.1.48_66956595233b000007ce4f9a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC))
- Ran patch without these changes and with improved tests and tests [failed](https://spruce.mongodb.com/task/evergreen_ui_deploy_utils_test_patch_cb12b0296cfbdb636293caa471c3a5013be3ef61_6695828e6065e50007ab64f9_24_07_15_20_12_05/logs?execution=0)

DEVPROD-7027: Fix email bug

---

packages/deploy-utils/package.json
packages/deploy-utils/src/email/email.test.ts
packages/deploy-utils/src/email/index.ts
packages/deploy-utils/src/email/utils.ts
packages/deploy-utils/src/utils/git/get-current-deployed-commit.ts
packages/deploy-utils/src/utils/git/index.ts

DEVPROD-7027
- Fix off-by-1 error in deploy emails. It was caused by [`getDate()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate) being 0-indexed even though the other 2 `get` functions I used are not... 🙄 I switched to trimming an ISO string because I think it's less error-prone.
- Also shorten commit hash in subject line as previous deploy emails used
- Update tests and run them in UTC for consistency across machines

DEVPROD-7027: Fix off-by-1 date error

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/Banners/RepotrackerBanner.tsx
apps/spruce/src/components/PatchesPage/ListArea/testData.ts
apps/spruce/src/components/TupleSelect/__snapshots__/TupleSelect_Default.storyshot
apps/spruce/src/components/TupleSelect/index.tsx
apps/spruce/src/components/TupleSelectWithRegexConditional/__snapshots__/TupleSelectWithRegexConditional_WithConditional.storyshot
apps/spruce/src/gql/client/cache.ts
apps/spruce/src/gql/fragments/patchesPage.graphql
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/commits/ViewToggle.tsx

DEVPROD-7846
Fix 422 errors on the Project Health page. They could be seen on the network tab in Firefox:
They no longer show up after applying the changes in this PR.
I also saw some cache errors for these queries so I tried to fix them:

DEVPROD-7846: Fix 422 errors on Project Health page

---

apps/spruce/src/pages/task/taskTabs/logs/LogTypes.tsx

DEVPROD-6861
https://github.com/evergreen-ci/evergreen/pull/8105 introduces a permissions check for the `Task.taskLogs` GQL field and this PR surfaces those errors in the UI when they occur.

DEVPROD-6861: Show error toast when fetching Task.taskLogs

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/projectSettings/github_app_settings.ts
apps/spruce/src/components/ConfirmationModal.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mutations/delete-github-app-credentials.graphql
apps/spruce/src/gql/mutations/index.ts
apps/spruce/src/pages/projectSettings/Tabs.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/AppSettingsTab.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/FieldTemplates.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/Fields/GithubAppActions.test.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/Fields/GithubAppActions.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/Fields/RequesterTypeField.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/Fields/index.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/getFormSchema.tsx
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/types.ts

DEVPROD-9282
Following the Figma designs, add button to delete GitHub credentials (because they are greyed out and uneditable after save).
- Jest tests for `DeleteAppCredentialsButton`
- Cypress tests for the actual deletion action

DEVPROD-9282: Add button to delete GitHub app credentials

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/components/TaskStatusIconLegend/index.tsx
apps/spruce/src/gql/generated/types.ts

DEVPROD-791
The `@leafygreen-ui/segemented-control` component uses a `z-index:3` property which causes the component to occasionally overlap the task icon tooltip. https://github.com/mongodb/leafygreen-ui/blob/6834540cba85e3d09b2d337df8f0c28ddd96ceec/packages/segmented-control/src/SegmentedControlOption/SegmentedControlOption.styles.ts#L93

DEVPROD-791 bump z-index on task icon tooltip to fix overlap on segmented control.

---

apps/spruce/src/gql/mocks/taskData.ts
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot
apps/spruce/src/pages/task/metadata/index.tsx

DEVPROD-9069
Users had difficulty identifying the failing command when looking at a task page. This PR aims to highlight the failing command in the task metadata more prominently.
https://www.figma.com/design/ZUhP5FPvKe67XZvpbpctt8/EXPO-3972%3A--Highlighting-Failing-Command?node-id=1-474&t=eYWPcitcmiYrxHaH-0

DEVPROD-9069 Highlight failing command more prominently

---

apps/parsley/src/components/Search/SearchBar/index.tsx
apps/parsley/src/hooks/useQueryParam/index.ts
apps/parsley/src/pages/LogDrop/ParseLogSelect/index.tsx
apps/parsley/src/snapshot.test.ts
apps/spruce/src/components/SearchableDropdown/index.tsx
apps/spruce/src/components/Spawn/utils/hostUptime.ts
apps/spruce/src/components/TextInputWithValidation/index.tsx
apps/spruce/src/hooks/useQueryParam/index.ts
apps/spruce/src/snapshot.test.ts
packages/deploy-utils/src/email/index.ts
packages/eslint-config/index.js
packages/lib/src/snapshot.test.ts

DEVPROD-9697
While working on a separate feature I noticed that `@evg-ui` dependencies were being sorted above internal deps and being sorted as if it was an external dependency. I split out this change to make the change sooner.

DEVPROD-9697 Update eslint sort rules so that evg-ui packages are not treated as external deps

---

apps/parsley/src/gql/generated/types.ts
apps/parsley/src/gql/queries/get-task.graphql
apps/parsley/src/hooks/useTaskQuery/index.ts
apps/parsley/src/pages/LogView/LoadingPage/useResolveLogURLAndRenderingType.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mocks/taskData.ts
apps/spruce/src/gql/queries/task.graphql
apps/spruce/src/pages/task/metadata/index.tsx

DEVPROD-9642
Ingest the failing command and use it in the Task Metadata panel as a backup value and in Parsley to find the failing log line. 
https://github.com/evergreen-ci/evergreen/pull/8166

DEVPROD-9642: Ingest TaskEndDetail.failingCommand GQL field

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot
apps/spruce/src/pages/task/metadata/index.tsx

DEVPROD-9751
Forgot to move the label out of the component body for longer descriptions

DEVPROD-9751 Fix label not being shown for Failing command

---

apps/spruce/cypress/integration/image/build_information.ts
apps/spruce/cypress/integration/preferences/notifications.ts
apps/spruce/cypress/integration/version/task_duration.ts
apps/spruce/src/components/Table/BaseTable.tsx
apps/spruce/src/constants/externalResources.ts
apps/spruce/src/constants/hosts.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/image-distros.graphql
apps/spruce/src/gql/queries/index.ts
apps/spruce/src/pages/image/DistrosTable/DistrosTable.test.tsx
apps/spruce/src/pages/image/DistrosTable/index.tsx
apps/spruce/src/pages/image/Header.tsx
apps/spruce/src/pages/image/ImageSelect/ImageSelect.test.tsx
apps/spruce/src/pages/image/Tabs.tsx
apps/spruce/src/pages/image/index.tsx
apps/spruce/src/pages/image/tabs/BuildInformationTab/index.tsx
apps/spruce/src/pages/image/tabs/index.tsx
apps/spruce/src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable_MultipleExecutions.storyshot
apps/spruce/src/pages/task/taskTabs/__snapshots__/ExecutionTasksTable_SingleExecution.storyshot
apps/spruce/src/pages/version/taskDuration/TaskDurationTable.test.tsx
apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_Default.storyshot
apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_LongContent.storyshot

DEVPROD-9562
Adds the distros table to the image page. 
I think we're missing some logic in the backend to hide admin-only distros for non-admin users — filed [DEVPROD-9743](https://jira.mongodb.org/browse/DEVPROD-9743) to fix that.
- Added unit test for `ImageSelect` because it was missing
- Added unit test for `DistrosTable`
- Added small Cypress test
- Some of the tests are failing because the `BaseTable` was not correctly setting the `data-cy-row` prop. I'll fix these after getting a review, since they introduce a lot of unrelated changes.

DEVPROD-9562: Create distros table on Build Information page

---

.github/pull_request_template.md
README.md
apps/spruce/src/components/styles/Layout.tsx
apps/spruce/src/pages/configurePatch/configurePatchCore/__snapshots__/ConfigurePatchCore_ConfigureTasksDefault.storyshot

DEVPROD-1065
Replace antd layout components with custom components that are approximately the same. This preserves the flexbox-based layout with semantic HTML tags
Bonus README and PR template improvements.

DEVPROD-1065: Remove antd layout

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx

DEVPROD-8684
Clarify expiration policy with a tooltip when a volume is mounted and expirable.

DEVPROD-8684: Clarify volume expiration policy in spawn volume table

---

apps/spruce/cypress/integration/projectSettings/github_app_settings.ts
apps/spruce/src/pages/projectSettings/tabs/GithubAppSettingsTab/getFormSchema.tsx

DEVPROD-9904
GitHub app private keys need the new line characters to be valid. Instead of having users manually add new line characters, and then escaping them ourselves, it's better to change it to a textarea so the new line characters are preserved.
Ran locally and then saved it with the textarea, the keys are successfully saved with the new lines. With the input, they were not.

DEVPROD-9904 Switch GitHub app private key from input to textarea

---

.evergreen/generate.yml
.evergreen/scripts/generate-tasks.js
.evergreen/scripts/parallelize-e2e.js
.evergreen/shared.yml

DEVPROD-928
- Parallelize Spruce e2e tests. This brings the wait time down from ~25 to ~10-12 minutes 😱 
- Programmatically bucket specs into N groups; I went with 4 groups for now but this is easy to play with. The buckets should have the same-ish size so that we don't have hugely different runtimes. To do this, the spec directories are sorted by size and then distributed into buckets. We could implement a smarter algorithm if this became a pain point.
- One consequence of programmatic bucketing is that the base status for each execution task is not necessarily meaningful. However, I don't anticipate that being a huge problem since the parent e2e_parallel base status is still correct and it's quite easy to see which test is failing. I think the reduced maintenance of not having to …

DEVPROD-928: Parallelize Spruce e2e tasks

---

.evergreen/scripts/generate-tasks.js

DEVPROD-9691
Stop excluding file deletions when generating CI tasks. The file deletions were being filtered out by the parameter [`--diff-filter=d`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203).
Running the commands, you can see that deletions were being explicitly excluded before:
* [Patch](https://spruce.mongodb.com/version/66c63249ad024100079cab88/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) where deletions were excluded — no tasks generated
* [Patch](https://spruce.mongodb.com/version/66c632bd9e3b5600075f991c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) where deletions were included — tasks were generated

DEVPROD-9691: Consider file deletions when generating CI tasks

---

apps/spruce/cypress/integration/image/event_log.ts
apps/spruce/src/pages/image/ImageEventLog/ImageEventLog.tsx
apps/spruce/src/pages/image/ImageEventLog/ImageEventLogTable.tsx
apps/spruce/src/pages/image/tabs/EventLogTab/EventLogTab.test.tsx

DEVPROD-7659
Add a search bar at the top of the Event Log page as a global filter. The global filter can be applied on the client side (LeafyGreen table should have built-in fields to support it).
Added Jest and Cypress tests.

DEVPROD-7659: Support global filter on Event Log page

---

apps/parsley/src/components/Accordion/__snapshots__/Accordion_Default.storyshot
apps/parsley/src/components/Accordion/index.tsx
apps/parsley/src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/__snapshots__/FilterGroup_Default.storyshot
apps/parsley/src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
apps/parsley/src/components/SidePanel/__snapshots__/SidePanel_Default.storyshot

DEVPROD-7394
Fix filter styles where the formatting is messed up. It looks like this right now on production:
(After consulting with Will on the design.)
https://github.com/user-attachments/assets/bc81a7f0-0933-4901-85b4-8ac086b5447d

DEVPROD-7394: Fix styles for long filter expressions

---

apps/parsley/package.json
apps/parsley/vite.config.ts
apps/spruce/config/vitest/setupTests.ts
apps/spruce/package.json
apps/spruce/vite.config.ts
package.json
packages/deploy-utils/package.json
packages/deploy-utils/vitest.config.ts
packages/lib/package.json
packages/lib/vitest.config.ts
yarn.lock

DEVPROD-8865
Upgrades Vitest. According to the [migration guide](https://vitest.dev/guide/migration.html#default-pool-is-forks), `pool: "forks"` is now the default setting.
- Tests should pass
- Checked that deploy tasks work since they rely on `vite-node`

DEVPROD-8865: Upgrade Vitest to v2.0.5

---

apps/spruce/cypress/integration/distroSettings/navigation.ts
apps/spruce/src/pages/distroSettings/index.tsx

DEVPROD-7661
Show links to image pages on distro pages (hidden on production).
- Cypress tests

DEVPROD-7661: Add links to image pages on Distro Settings page

---

apps/spruce/src/pages/configurePatch/configurePatchCore/__snapshots__/ConfigurePatchCore_ConfigureTasksDefault.storyshot
apps/spruce/src/pages/configurePatch/configurePatchCore/index.tsx
apps/spruce/src/pages/container/Metadata/index.tsx
apps/spruce/src/pages/host/Metadata.tsx
apps/spruce/src/pages/jobLogs/Metadata.tsx
apps/spruce/src/pages/version/Metadata.tsx

DEVPROD-10353
* Updates the remaining metadata panels on spruce to use the new bold metadata label labels introduced in DEVPROD-4512
* Removes the commit queue link from patch metadata

DEVPROD-10353 Update metadata panels on spruce to use new bold label design

---

apps/spruce/src/components/CodeChanges/index.tsx
apps/spruce/src/pages/Version.tsx
apps/spruce/src/pages/version/VersionTabs.tsx

DEVPROD-7054
Apparently the GitHub merge queue API is not capable of returning the changes included in the patches, so there will never be any changes to show. This PR makes it so that we don't show the changes tab for GitHub merge queue patches.

DEVPROD-7054: Omit changes tab for GitHub merge queue patches

---

apps/spruce/src/pages/version/Metadata.tsx

DEVPROD-10353
Looks like i missed a spot in 705940bd2747b2f706440f94384457f9aeff62a6 
Before:
After:

DEVPROD-10353 Make base commit label in patch metadata bold

---

apps/spruce/cypress/integration/waterfall/navigation.ts
apps/spruce/src/components/Content/index.tsx
apps/spruce/src/constants/featureFlags.ts
apps/spruce/src/constants/routes.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/Waterfall.tsx
apps/spruce/src/pages/waterfall/index.tsx

DEVPROD-10175
Adds new route for the new waterfall page. This page is not visible on production.
(The text on the page is just a placeholder to show that the route & slug is working)
- Added Cypress test

DEVPROD-10175: Create waterfall page route

---

apps/spruce/cypress/integration/distroSettings/project_section.ts
apps/spruce/src/pages/distroSettings/tabs/ProjectTab/getFormSchema.ts

DEVPROD-10482
Updates the label used on the distro settings valid projects section to make it more clear that it is expecting a project id instead of an identifier

DEVPROD-10482 Update valid projects label to use ID instead of name

---

apps/spruce/cypress/integration/image/navigation.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mocks/taskData.ts
apps/spruce/src/gql/queries/task.graphql
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_OOMTracker.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot
apps/spruce/src/pages/task/metadata/index.tsx

DEVPROD-7660
Reverts my previous revert. The issue has been fixed on the backend and the page should no longer crash for any task.
- Cypress tests

DEVPROD-7660: Add link to image page in task metadata

---

packages/lib/src/utils/observability/honeycomb.ts

DEVPROD-11410
After a ton of debugging, I finally identified why Parsley was throwing CORS errors whenever we tried to instrument requests.
Initially, I suspected that the Honeycomb collector returning a CORS error might have caused the same error to propagate to requests made to Evergreen. However, after fixing the CORS settings in the Honeycomb collector, the error persisted.
My next hypothesis was that the instrumentation itself was causing issues since disabling Honeycomb resolved the bug. It turns out that `@opentelemetry/instrumentation-fetch` was the culprit. This package instruments all fetch requests the app makes. For some reason, on certain Parsley requests—specifically when we utilize a [`streamedFetch` ](https://github.com/evergreen-ci/ui/blob/5595ff5155b7bf60bb778329061a10753 …

DEVPROD-11410 Don't init @opentelemetry/instrumentation-fetch if running on parsley

---

apps/parsley/src/gql/generated/types.ts
apps/parsley/src/utils/string/index.ts
apps/parsley/src/utils/string/string.test.ts

DEVPROD-9738
It's possible for the user to force a failed status on a task by calling the task_status API within a command. In this case, there may not be an explicit failure logged but the command section should still be matched on with the jump to failing line feature.

DEVPROD-9738: Match on user defined failing commands

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/utils/string/index.ts
apps/spruce/src/utils/string/string.test.ts

DEVPROD-10319
A user reported that the task durations were out of order. It seems like the values in the task duration table are sorted correctly, but the value that we report is not correct.
(Properly renders `1d` now)
- Added unit test

DEVPROD-10319: Fix time conversion logic in msToDuration

---

apps/spruce/cypress/integration/page_tabs.ts
apps/spruce/cypress/integration/version/task_duration.ts
apps/spruce/src/analytics/version/useVersionAnalytics.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/hooks/useTableSort/index.ts
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable.tsx
apps/spruce/src/pages/task/taskTabs/TestsTable.tsx
apps/spruce/src/pages/version/TaskDuration.tsx
apps/spruce/src/pages/version/taskDuration/TaskDurationTable.test.tsx
apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx
apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_Default.storyshot
apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_LongContent.storyshot
apps/spruce/src/pages/version/useQueryVariables/index.ts
apps/spruce/src/pages/version/useQueryVariables/useQueryVariables.test.tsx

DEVPROD-828
These code changes add multisort to the Task Duration Table by utilizing the `useTableSort` hook. 
Tickets produced during this work: 
https://jira.mongodb.org/browse/DEVPROD-11421
https://jira.mongodb.org/browse/DEVPROD-11539
https://jira.mongodb.org/browse/DEVPROD-11537
https://jira.mongodb.org/browse/DEVPROD-11422

DEVPROD-828: Add multisort to TaskDurationTable

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/hosts/update_status_modal.ts
apps/spruce/src/gql/generated/types.ts

DEVPROD-5753
Update the "update host status" e2e test to select an option that's not `decommissioned`. The EVG pr updated the test data and the resolver was outputting an error message that was too large for the current electron window size. 
https://github.com/evergreen-ci/evergreen/pull/8337

DEVPROD-5753: Update test to accommodate updated test data

---

apps/spruce/src/pages/taskQueue/index.tsx

DEVPROD-7848
While loading, show "Loading" badge in distro select dropdown instead of 0 tasks/0 hosts badges

DEVPROD-7848: Add loading state to task queue select

---

.evergreen/shared.yml
apps/parsley/src/gql/generated/types.ts

DEVPROD-11701
Adds a timeout for setup-node. I took a look at a few tasks and this step is usually pretty quick usually only a few seconds. So I figured a 1 minute timeout should be sufficient to catch if we are downloading node or if we are doing something else.

DEVPROD-11701 Configure timeout for setup-node script

---

.evergreen/deploy.yml
apps/parsley/src/main.tsx
apps/spruce/src/index.tsx
packages/lib/src/utils/observability/honeycomb.ts

DEVPROD-11852
This PR adds an environment field for all spans the apps send. This will allow for filtering of honeycomb spans when performing queries. `environment = beta` will show only spruce beta or parsley beta spans.
Example query:
https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/spruce/result/dot6UtisTcA?tab=traces

DEVPROD-11852 Tag release environment in all OTEL spans and support beta tracking in honeycomb

---

apps/spruce/src/pages/waterfall/index.tsx

DEVPROD-11900
Add banner directing users to give feedback on the waterfall
I made the banner non-dismissible because I think having it visible will help reinforce that this page is a work in progress

DEVPROD-11900: Add alpha info banner to beta deploys

---

apps/spruce/cypress/integration/spawn/host.ts

DEVPROD-9478
I noticed that these tests broke again because .next() would be undefined. I refactored this test to not rely on `.next()` and to instead check if the cell has a sibling. If it does then we can select it, otherwise toggle the next month logic.

DEVPROD-9478 Refactor date selection logic in Spawn Host page test

---

apps/spruce/cypress/integration/task/execution_task_table.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/hooks/useTableSort/index.ts
apps/spruce/src/pages/hosts/utils.ts
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable.tsx
apps/spruce/src/pages/task/taskTabs/TestsTable.tsx
apps/spruce/src/pages/version/TaskDuration.tsx
apps/spruce/src/pages/version/tasks/PatchTasksTable.tsx

DEVPROD-1770
Replace `useUpdateURLQueryParams` with `useQueryParams` or `useQueryParam` in table components. I also updated ExectionTaskTable so rely on sorts instead of sortBy and sortDir because it made these code changes simpler.

DEVPROD-1770: Use modern query param hooks with tables

---

apps/parsley/src/components/ErrorHandling/Sentry.tsx
apps/parsley/src/components/ErrorHandling/initialize.test.ts
apps/spruce/src/components/ErrorHandling/Sentry.tsx
apps/spruce/src/components/ErrorHandling/initialize.test.ts

DEVPROD-12038
Sentry currently samples at a 50% rate but this sometimes results in scenarios where we don't log crucial errors. We have reduced the overall logging volume of sentry so it should be safe to increase this value

DEVPROD-12038 Remove sentry sampling

---

apps/parsley/src/utils/resmoke/helpers.test.ts
apps/parsley/src/utils/resmoke/helpers.ts

DEVPROD-12078
Some lines from the log linked in the ticket are not getting parsed properly because our regex for ctx is a little too strict. We need to allow `.` character.
- Added unit test
- Confirmed manually the lines are getting parsed properly using the link from the ticket

DEVPROD-12078: Allow dot character in ctx regex

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/analytics/task/useTaskAnalytics.ts
apps/spruce/src/analytics/version/useVersionAnalytics.ts

DEVPROD-12386
This change adds automatic tracking of requesters for version and task interactions in honeycomb. This will be useful to determine what types of actions people take on different types of version and task pages.

DEVPROD-12386 Track `is_patch` and `requester` for tasks and versions

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/waterfall.graphql
apps/spruce/src/pages/waterfall/InactiveVersions/InactiveVersionsModal.stories.tsx
apps/spruce/src/pages/waterfall/InactiveVersions/InactiveVersionsModal.tsx
apps/spruce/src/pages/waterfall/InactiveVersions/__snapshots__/InactiveVersionsModal_Broken.storyshot
apps/spruce/src/pages/waterfall/InactiveVersions/__snapshots__/InactiveVersionsModal_Default.storyshot
apps/spruce/src/pages/waterfall/InactiveVersions/__snapshots__/InactiveVersionsModal_Filtered.storyshot
apps/spruce/src/pages/waterfall/InactiveVersions/__snapshots__/InactiveVersionsModal_FilteredAndInactive.storyshot
apps/spruce/src/pages/waterfall/InactiveVersions/index.tsx
apps/spruce/src/pages/waterfall/VersionLabel/VersionLabel.stories.tsx
apps/spruce/src/pages/waterfall/VersionLabel/__snapshots__/VersionLabel_Broken.storyshot
apps/spruce/src/pages/waterfall/VersionLabel/__snapshots__/VersionLabel_Default.storyshot
apps/spruce/src/pages/waterfall/VersionLabel/__snapshots__/VersionLabel_GitTag.storyshot
apps/spruce/src/pages/waterfall/VersionLabel/__snapshots__/VersionLabel_SmallSize.storyshot
apps/spruce/src/pages/waterfall/VersionLabel/__snapshots__/VersionLabel_UpstreamProject.storyshot
apps/spruce/src/pages/waterfall/VersionLabel/index.tsx
apps/spruce/src/pages/waterfall/WaterfallGrid.tsx
apps/spruce/src/pages/waterfall/index.tsx
apps/spruce/src/pages/waterfall/testData.ts
apps/spruce/src/pages/waterfall/useFilters.test.tsx

DEVPROD-11706
Add filtered commits—now considered "inactive" on the waterfall—to the inactive version modal.
If filtered but activated commits are present, unactivated commits will use disabled text.
Add stories for VersionLabel and InactiveVersionsModal

DEVPROD-11706: Add filtered commits to inactive modal

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/package.json
apps/spruce/src/gql/GQLWrapper.tsx
apps/spruce/src/gql/client/link/index.ts
apps/spruce/src/gql/client/link/logGQLErrorsLink.test.ts
apps/spruce/src/gql/client/link/logGQLErrorsLink.ts
apps/spruce/src/gql/client/link/logGQLToSentryLink.ts
apps/spruce/src/gql/fetch/index.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/hooks/useCreateGQLClient/index.ts
apps/spruce/src/pages/Login.tsx
apps/spruce/src/utils/object/index.ts
apps/spruce/src/utils/request.test.ts
apps/spruce/src/utils/request.ts
packages/lib/src/utils/object/index.ts
packages/lib/src/utils/object/object.test.ts
packages/lib/src/utils/request/index.ts
packages/lib/src/utils/request/request.test.ts
yarn.lock

DEVPROD-7857
Send immediate Sentry alerts for 422 errors.
This PR also moves certain utils up to the `lib` folder so that they can be used in the upcoming PR for Parsley, which requires a lot more changes.
- [Sample issue](https://mongodb-org.sentry.io/issues/6025875166/?referrer=slack&notification_uuid=a77e421c-39d8-4d51-91ce-08ee813d1b3c&environment=staging&alert_rule_id=14677842&alert_type=issue)

DEVPROD-7857: Send Sentry alerts for 422 errors in Spruce

---

apps/spruce/src/pages/projectSettings/CreateProjectModal.tsx
apps/spruce/src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx

DEVPROD-10151
Rename "Owner" ➡️ "GitHub Organization"

DEVPROD-10151: Rename owner field in project settings

---

apps/spruce/src/constants/triggers.ts

DEVPROD-11667
Add Git Tag as an option for project notifications. Once deployed, I can edit our subscription.
- Updated `commit-queue-sandbox` project subscriptions to listen for any task failure on git tag version. Then created a [git tag version](https://spruce-staging.corp.mongodb.com/version/sandbox_testtag10_672a78e7f3b818000df15234/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). Afterwards, received this notification:

DEVPROD-11667: Support git tag requester for project notifications

---

apps/parsley/src/constants/logURLTemplates.ts
apps/parsley/src/gql/generated/types.ts
apps/parsley/src/pages/LogView/LoadingPage/useResolveLogURLAndRenderingType.test.tsx

DEVPROD-12638
Fix log template by escaping slash.
Visit http://localhost:5173/resmoke/mongosync_1.9.x_v70_to_v70_rhel80_ctc_custom_replica_sets_fsm_patch_111e453563b31a35f322e74ffd909fdbb99cbc0e_672bb2ee8de6fe0006f70397_24_11_06_18_18_23/0/job1/all?bookmarks=0,5545359: no instances of `job10`, which indicated incorrect escaping, are present.

DEVPROD-12638: Fix job log URL template

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/waterfall.graphql
apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/index.tsx

DEVPROD-12509
- Use display status in waterfall
- Also fix spacing so that beta site banner has some padding
https://github.com/evergreen-ci/evergreen/pull/8454

DEVPROD-12509: Use display status in waterfall

---

apps/spruce/src/components/Spawn/editHostModal/utils.ts
apps/spruce/src/components/Spawn/utils/hostUptime.ts
apps/spruce/src/pages/spawn/spawnHost/EditSpawnHostModal.tsx
apps/spruce/src/pages/spawn/spawnHost/spawnHostButton/SpawnHostModal.tsx

DEVPROD-12004
This bug is caused by the fact that the user has a public key with an empty string name (`""`). I have no idea how they were able to do this, because we have checks to make sure this doesn't happen. I have told the user in the ticket to delete their empty key.
Regardless, the error behavior can be fixed by making sure that we send the entire public key document when editing the host.
Separately, fixed nearby TypeScript errors and updated deprecated `ConfirmationModal` props.
1. Have a public key with an empty string name (`""`). I had to add via the database since you cannot do this from the UI.
2. Have a public key with a non-empty name. Use the **same key** as the public key above.
3. Try to edit host with your public key. It will fail. This is because it diffs the keys …

DEVPROD-12004: Send entire public key document when editing spawn host

---

apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/WaterfallGrid.tsx
apps/spruce/src/pages/waterfall/useFilters.ts

DEVPROD-11880
Position tooltip to the left of the task box in the last active version column so that the tooltip is not cut off at the edge of the window.

DEVPROD-11880: Reposition tooltip in last active version column

---

apps/spruce/cypress/integration/hosts/select_hosts.ts
apps/spruce/cypress/integration/hosts/update_status_modal.ts

DEVPROD-5753
This is to be able to merge Arjun's PR. 
Although the copy itself is generated on the frontend, the number comes from the backend, so we should remove it since it's subject to change.
* evergreen-ci/evergreen/pull/8460

DEVPROD-5753: Remove host counts in `validateToast`

---

apps/parsley/src/analytics/useAnalyticAttributes.ts
apps/parsley/src/pages/index.tsx
apps/spruce/src/analytics/useAnalyticsAttributes.ts
apps/spruce/src/components/Content/Layout.tsx

DEVPROD-12802
It looks like `user.id` is not always reliably displayed in honeycomb events. I think this was caused by relying on localstorage to populate the user.id since sometimes it may not be populated at the point we request it or it may have been populated after the hook to write has already run.

DEVPROD-12802 Ensure userId AttributeStore reads and writes are not stale

---

apps/parsley/src/gql/generated/types.ts
packages/deploy-utils/src/prepare-prod-deploy/index.ts
packages/deploy-utils/src/prepare-prod-deploy/prepare-prod-deploy.test.ts

DEVPROD-13059
Its a little scary when it jumps straight through the deploy without giving you a chance to even read what commits are in it. This adds a safeguard and prompts the user to confirm or cancel the prompt after telling them what is in the deploy.

DEVPROD-13059 Add confirmation prompt for deploys

---

apps/spruce/src/components/Settings/EventLog/eventLogDiffs.test.ts
apps/spruce/src/components/Settings/EventLog/eventLogDiffs.ts

DEVPROD-12987
Fix regex used to format event log entries that contain an array so that numbers in variable names are not incorrectly array-ified.
Add test that fails without change

DEVPROD-12987: Fix event log key renderer

---

apps/spruce/cypress/integration/myPatches/my_patches.ts
apps/spruce/src/components/PatchStatusBadge.tsx
apps/spruce/src/components/PatchesPage/StatusSelector.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/projectSettings/tabs/PatchAliasesTab/transformers.ts
apps/spruce/src/pages/projectSettings/tabs/utils/types.ts
apps/spruce/src/types/patch.ts

DEVPROD-13116
I found some todos that were left over from https://jira.mongodb.org/browse/DEVPROD-650 around removing a legacy success status. It looks like the backend ticket was completed but the frontend TODO's remained
Some backend data will need to change 
https://github.com/evergreen-ci/evergreen/pull/8514

DEVPROD-13116 Remove deprecated legacy success status

---

apps/spruce/src/pages/waterfall/index.tsx
apps/spruce/src/pages/waterfall/styles.ts

DEVPROD-11708
Based on feedback in the focus group Slack channel and a conversation with Will, users seem to actually prefer fewer commits and lots more space for build variants on a big screen. Our grid scales well enough to handle this, so this PR just removes the TODOs around a dynamic commit limit.

DEVPROD-11708: Remove TODOs for dynamic commit count

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mutations/schedule-patch.graphql
apps/spruce/src/pages/configurePatch/configurePatchCore/index.tsx
apps/spruce/src/pages/version/VersionTabs.tsx

DEVPROD-10037
Update the Schedule patches confirmation toast to indicate that child patches have been scheduled.
Also fix a bug where the downstream projects tab is initially empty. I think a combination of both of these lead to the confusion in the ticket.

DEVPROD-10037 Indicate downstream patches have been scheduled

---

apps/spruce/src/components/PatchesPage/ListArea/PatchCard/DropdownMenu.tsx
apps/spruce/src/components/PatchesPage/ListArea/PatchCard/index.tsx
apps/spruce/src/components/PatchesPage/ListArea/testData.ts
apps/spruce/src/gql/fragments/patchesPage.graphql
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/Version.tsx

DEVPROD-9579
Disable reconfiguring a patch if it is a GitHub merge queue patch.

DEVPROD-9579: Disable reconfigure button for GitHub merge queue patches

---

apps/spruce/src/components/TasksTable/Columns.tsx
apps/spruce/src/components/TasksTable/types.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/task.graphql
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable/ExecutionTasksTable.stories.tsx
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable/__snapshots__/ExecutionTasksTable_MultipleExecutions.storyshot
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable/__snapshots__/ExecutionTasksTable_SingleExecution.storyshot
apps/spruce/src/pages/task/taskTabs/ExecutionTasksTable/index.tsx

DEVPROD-13928
Display statuses weren't being populated for the Execution Tasks table due to https://github.com/evergreen-ci/ui/pull/534
Before:
After:

DEVPROD-13928 Ensure displayStatus is used for ExecutionTasksTable

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/hooks/useBreakingTask/index.ts
apps/spruce/src/hooks/useLastExecutedTask/index.ts
apps/spruce/src/hooks/useLastPassingTask/index.ts
apps/spruce/src/hooks/useParentTask/index.ts
apps/spruce/src/utils/getTaskFromMainlineCommitsQuery.ts

DEVPROD-13931
Adds an additional check that validates that the mainline commits query has returned data before trying to access it.
No longer errors

DEVPROD-13931 Ensure mainline commits are defined before trying to get task data

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/waterfall.graphql
apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/useFilters.test.tsx
apps/spruce/src/pages/waterfall/useFilters.ts

DEVPROD-13825
Use `displayStatusCache` instead of `displayStatus` field. Also use `status` as a fallback for tasks that lack `displayStatusCache`.
Updated tests
https://github.com/evergreen-ci/evergreen/pull/8595

DEVPROD-13825: Use displayStatusCache instead of displayStatus

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/spawn/host.ts
apps/spruce/src/components/Spawn/spawnHostModal/getFormSchema.tsx
apps/spruce/src/components/Spawn/spawnHostModal/transformer.test.ts
apps/spruce/src/components/Spawn/spawnHostModal/transformer.ts
apps/spruce/src/components/Spawn/spawnHostModal/types.ts
apps/spruce/src/gql/fragments/projectSettings/general.graphql
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/spawn-task.graphql
apps/spruce/src/pages/projectSettings/CopyProjectModal.test.tsx
apps/spruce/src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx
apps/spruce/src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
apps/spruce/src/pages/projectSettings/tabs/GeneralTab/transformers.test.ts
apps/spruce/src/pages/projectSettings/tabs/GeneralTab/transformers.ts
apps/spruce/src/pages/projectSettings/tabs/GeneralTab/types.ts
apps/spruce/src/pages/projectSettings/tabs/testData.ts

DEVPROD-13969
This removes the task sync project settings and the checkbox for spawnhosts.
I'm not that familiar with the UI codebase so please feel free to nitpick or anything! 
New:
Old:
Saved settings and it worked as normal.
[#8637](https://github.com/evergreen-ci/evergreen/pull/8637) has to be merged after this change.

DEVPROD-13969: Remove task sync project settings [minor]

---

apps/spruce/src/pages/waterfall/DateFilter/index.tsx

DEVPROD-12595
This should have been done in #561, but for the same reasons, remove the React transition from the date selector. A loading state is more effective here.

DEVPROD-12595: Remove transition for date selector

---

apps/parsley/src/components/DetailsMenu/DetailsMenuCard/ButtonRow/index.tsx
apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/task/files_tables.ts
apps/spruce/src/components/CodeChanges/index.tsx
apps/spruce/src/components/CodeChangesTable/index.tsx
apps/spruce/src/components/WelcomeModal/WelcomeModal.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/jobLogs/Metadata.tsx
apps/spruce/src/pages/task/taskTabs/FileTable/GroupedFileTable/__snapshots__/GroupedFileTable_DefaultTable.storyshot
apps/spruce/src/pages/task/taskTabs/FileTable/GroupedFileTable/index.tsx
apps/spruce/src/pages/task/taskTabs/Logs.tsx
apps/spruce/src/pages/task/taskTabs/testsTable/LogsColumn.tsx
apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/FailedTestGroupTable/index.tsx

DEVPROD-14813
This PR updates most links people usually interact with to open in the current browser tab. I kept some links such as links to external wikis or links that occur in forms the same so they don't accidentally overwrite what ever the user is working on.

DEVPROD-14813 Update links to open internal links in the same tab

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/waterfall.graphql
apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/types.ts
apps/spruce/src/pages/waterfall/useFilters.test.tsx

DEVPROD-14495
Ahead of some changes to the GraphQL schema to better support caching in DEVPROD-12696, clean up waterfall types. Using a few types that are not inferred from generated types will allow us to more easily make changes and ensure that the required data is still present.

DEVPROD-14495: Clean up waterfall types

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/utils/getTaskFromMainlineCommitsQuery.ts
packages/lib/src/components/styles/Link.tsx

DEVPROD-14335
This error has been very noisy and occurs because sometimes tasks just don't have a last passing version especially if they are newly created so this query will silently error in the background. I removed the error log since this is an acceptable scenario.
* Also fixed a random ref error I saw while I was investigating this also
No more errors in the console

DEVPROD-14335 Remove error logging for missing build variants

---

apps/spruce/src/components/Banners/SiteBanner.tsx

DEVPROD-NNNNN
Align Spruce's green banner to look more like Evergreen's by using the announcement icon. A sitewide success banner has a limited use case anyway.

DEVPROD-14682: Make success banner look more like an announcement

---

apps/spruce/src/analytics/waterfall/useWaterfallAnalytics.ts
apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/WaterfallGrid.tsx

DEVPROD-14700
Add analytics event to track when pin button is clicked

DEVPROD-14700: Add pin analytics event

---

apps/parsley/cypress/support/index.ts
apps/spruce/cypress/support/e2e.ts
scripts/evg-db-ops.sh

DEVPROD-13428
The tests in `host_buttons.ts` fail because the host is sometimes in a decommissioned state. You cannot reprovision or restart Jasper for a decommissioned host. 
True, it seems like this should be impossible because the database should reset after every test that executes a mutation.
In all of the test failures linked in the corresponding JIRA ticket, the test that runs directly before is `host_update_status.ts`. This test calls a mutation that creates a job in Amboy called EnqueueTerminateHostJob.
I think the test was flaky due to a race condition. The two patterns would be:
*  Sometimes it would succeed because the Amboy job ran first and marked the host as decommissioned. Then we cleared the database and the host was reset correctly.
* Sometimes it would fail because we …

DEVPROD-13428: Reset Amboy database in e2e tests when mutations enqueue jobs

---

.evergreen/scripts/generate-parallel-e2e-tasks.js
.evergreen/shared.yml

DEVPROD-13189
https://github.com/evergreen-ci/evergreen/pull/8710 introduces a new [non-public repo](https://github.com/evergreen-ci/test-selection-client) as a Go module. Since the UI compiles Evergreen as part of the e2e tests, it needs to have a GitHub token that can clone the non-public repo. I copied the relevant project YAML configuration for generating/setting the token from that PR and set up the GitHub app in the evergreen-ui project settings.
N/A
e2e tests pass.
https://github.com/evergreen-ci/evergreen/pull/8710

DEVPROD-13189: use GitHub dynamic token for downloading Go modules

---

.backstage.yml

[DPLATFORMS-390](https://jira.mongodb.org/browse/DPLATFORMS-390)
Description
Goes with https://github.com/10gen/devprod-idp/pull/21. The idea is to store the information about a backstage entity alongside the code that's responsible for it. The schema lives [here](https://backstage.io/docs/features/software-catalog/descriptor-format).
https://github.com/evergreen-ci/evergreen/pull/8737

DPLATFORMS-390 add backstage entity description

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/waterfall/BuildRow.tsx
apps/spruce/src/pages/waterfall/constants.ts

DEVPROD-14877
Prioritizes `status` over `displayStatusCache` if the version was created before the `displayStatusCache` changes were finalized. It can be removed after a year (task TTL).
I based the timestamp off of evergreen-ci/evergreen/pull/8644, because it's the last change, but let me know if that's wrong 😅
- Tasks mentioned in the ticket now correctly show as succeeded

DEVPROD-14877: Use `status` if version was created before `displayStatusCache` was added

---

apps/spruce/cypress/integration/spawn/volume.ts
apps/spruce/src/components/Spawn/editVolumeModal/getFormSchema.tsx
apps/spruce/src/components/Spawn/editVolumeModal/transformer.ts
apps/spruce/src/components/Spawn/editVolumeModal/types.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/spawn/SpawnVolume.tsx
apps/spruce/src/pages/spawn/spawnVolume/SpawnVolumeTable.tsx
apps/spruce/src/pages/spawn/spawnVolume/SpawnVolumeTableActions.tsx
apps/spruce/src/pages/spawn/spawnVolume/spawnVolumeTableActions/EditButton.tsx
apps/spruce/src/pages/spawn/spawnVolume/spawnVolumeTableActions/EditVolumeModal.tsx

DEVPROD-12285
Shows size as a field in the `EditVolumeModal`.
Volume size can only be increased, not decreased. This is simply a rule that comes from [AWS](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-volume.html#options)
* Add Cypress tests

DEVPROD-12285: Allow users to modify volume size

---

apps/spruce/src/components/MetadataCard.tsx
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/configurePatch/configurePatchCore/index.tsx
apps/spruce/src/pages/container/Metadata/index.tsx
apps/spruce/src/pages/host/Metadata.tsx
apps/spruce/src/pages/jobLogs/Metadata.tsx
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_OOMTracker.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot
apps/spruce/src/pages/task/metadata/index.tsx
apps/spruce/src/pages/version/BuildVariantCard/index.tsx
apps/spruce/src/pages/version/Metadata.tsx

DEVPROD-14935
Convert `MetadataTitle` into a `title` prop for the `MetadataCard` component. This allows the card to still show the title while displaying the loading state, and is also a better pattern in general imo.
Would also like to combine `MetadataLabel` and `MetadataItem` in a similar way, but that feels like a different ticket.

DEVPROD-14935: Show metadata title while loading

---

apps/parsley/cypress/support/commands.ts
apps/parsley/cypress/support/index.ts
apps/parsley/src/components/SidePanel/index.tsx
apps/parsley/src/constants/cookies.ts
apps/parsley/src/gql/generated/types.ts

DEVPROD-15077
Use new cookie that doesn't behave like a flag to set the sidenav's open state when the user collapses or expands it.

DEVPROD-15077: Fix menu collapsed state

---

apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mutations/schedule-tasks.graphql
apps/spruce/src/gql/mutations/unschedule-task.graphql

DEVPROD-1031
The schedule and unschedule button disabled states on the Task page were not updating after clicking because the mutations did not fetch canSchedule and canUnschedule. These code changes add those fields so they can get integrated into the gql cache and update the button states.

DEVPROD-1031: Update schedule/unschedule button state on Task page

---

apps/spruce/src/components/Banners/GithubUsernameBanner.tsx
apps/spruce/src/components/Banners/SlackNotificationBanner.tsx
apps/spruce/src/components/Spawn/spawnHostModal/useLoadFormSchemaData.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mocks/getSpruceConfig.ts
apps/spruce/src/gql/queries/user-settings.graphql
apps/spruce/src/hooks/useUserSettings/index.ts
apps/spruce/src/hooks/useUserTimeZone/index.ts

DEVPROD-13093
Replace `userSettings` query with `user.settings`. I'll open an evergreen PR to remove the resolver as well, and merge it once this is deployed for simple revertability.

DEVPROD-13093: Remove userSettings query

---

apps/spruce/src/components/ScheduleTasksModal/index.tsx
apps/spruce/src/components/VersionRestartModal/VersionRestartModal.tsx

DEVPROD-12122
Freeze the schedule task banner warning to the top of the schedule task modal so it isn't in a scrollable area.

DEVPROD-12122 Move schedule task warning banner to a fixed position

---

apps/spruce/src/components/MetadataCard.tsx
apps/spruce/src/components/MetadataCard/MetadataCard.stories.tsx
apps/spruce/src/components/MetadataCard/__snapshots__/MetadataCard_Default.storyshot
apps/spruce/src/components/MetadataCard/index.tsx
apps/spruce/src/components/PageSizeSelector/__snapshots__/PageSizeSelector_Default.storyshot
apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm_Example1.storyshot
apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm_Example2.storyshot
apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm_Example3.storyshot
apps/spruce/src/components/Table/TableControl/__snapshots__/TableControl_Default.storyshot
apps/spruce/src/components/TextInputWithValidation/__snapshots__/TextInputWithValidation_Default.storyshot
apps/spruce/src/components/TreeSelect/__snapshots__/TreeSelect_Default.storyshot
apps/spruce/src/components/TupleSelect/__snapshots__/TupleSelect_Default.storyshot
apps/spruce/src/components/TupleSelectWithRegexConditional/__snapshots__/TupleSelectWithRegexConditional_WithConditional.storyshot
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/commits/__snapshots__/ProjectHealth_Default.storyshot
apps/spruce/src/pages/configurePatch/configurePatchCore/index.tsx
apps/spruce/src/pages/container/Metadata/index.tsx
apps/spruce/src/pages/host/HostTable/__snapshots__/HostTable_Default.storyshot
apps/spruce/src/pages/host/Metadata.tsx
apps/spruce/src/pages/jobLogs/Metadata.tsx
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_OOMTracker.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot
apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot
apps/spruce/src/pages/task/metadata/index.tsx
apps/spruce/src/pages/version/BuildVariantCard/__snapshots__/BuildVariantCard_Default.storyshot
apps/spruce/src/pages/version/BuildVariantCard/index.tsx
apps/spruce/src/pages/version/Metadata.tsx
apps/spruce/src/pages/version/ParametersModal/__snapshots__/ParametersModal_Default.storyshot

DEVPROD-15373
My changes in DEVPROD-11546 ended up inadvertently breaking the spacing between metadata items. (I wonder why I didn't notice this).
Also added a storybook story for this to catch it in the future. 
Refactored component to use Leafygreen loading skeleton
Add leaf

DEVPROD-15373 Fix metadata spacing

---

apps/spruce/src/pages/waterfall/WaterfallMenu/JumpToMostRecent.tsx

DEVPROD-15061
Also clears date and revision query params when jumping to most recent commit.

DEVPROD-15061: Clear date and revision filters when jumping to most recent commit

---

apps/spruce/src/pages/task/metadata/index.tsx

DEVPROD-8259
Activated and ingest time are now rendered separately with updated labels.

DEVPROD-8259: Display ingest and activated time separately in task metadata panel

---

apps/spruce/cypress/integration/waterfall/filters.ts
apps/spruce/src/constants/routes.test.ts
apps/spruce/src/constants/routes.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/waterfall/WaterfallFilters.tsx

DEVPROD-14702
These code changes apply the current waterfall task filters when selecting a new project

DEVPROD-14702: Preserve Task Status filters when switching waterfall projects

---

apps/spruce/src/pages/Version.tsx
apps/spruce/src/pages/version/BuildVariantCard/index.tsx
apps/spruce/src/pages/version/Metadata.tsx

DEVPROD-15569
A regression was introduced that caused the version page to display a loading screen every time a user would switch tabs and the page would background poll. This fixes it so we only show the loading screen if we don't already have data for the page. I also fixed some ts warnings.
Page no longer displays a loading screen when switching tabs

DEVPROD-15569 Fix bug causing page to display a loading screen on poll

---

apps/spruce/cypress/integration/spawn/host.ts
apps/spruce/src/components/Spawn/spawnHostModal/getFormSchema.tsx
apps/spruce/src/gql/generated/types.ts

DEVPROD-15439
This checkbox is hidden if a project doesn't have a setup script defined, so it won't affect other projects.

DEVPROD-15439: Check project setup script option by default

---

apps/spruce/cypress/integration/task/task_history.ts
apps/spruce/src/constants/featureFlags.ts
apps/spruce/src/constants/requesters.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/task/TaskTabs.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/index.tsx
apps/spruce/src/pages/waterfall/RequesterFilter/index.tsx
apps/spruce/src/types/task.ts

DEVPROD-15848
Adds a tab for task history for mainline commits only.
- Added Cypress test

DEVPROD-15848: Add tab for task history

---

apps/parsley/src/analytics/loadingPage/useLogDownloadAnalytics.ts
apps/parsley/src/gql/generated/types.ts
apps/parsley/src/hooks/useLogDownloader/index.ts

DEVPROD-16157
While looking at our analytics, I noticed we weren't logging the reason for failed downloads.

DEVPROD-16157 Add reason field to log download analytics for better error tracking

---

apps/parsley/src/App.tsx
apps/parsley/src/gql/generated/types.ts
apps/spruce/src/App.tsx
apps/spruce/src/gql/generated/types.ts
packages/lib/src/components/ErrorBoundary/ErrorBoundary.test.tsx
packages/lib/src/components/ErrorBoundary/ErrorFallback/ErrorFallback.tsx
packages/lib/src/components/ErrorBoundary/ErrorFallback/__snapshots__/ErrorFallback_DefaultError.storyshot
packages/lib/src/components/ErrorBoundary/SentryErrorBoundary.tsx
packages/lib/src/components/ErrorBoundary/utils.ts

DEVPROD-15374 
Error boundary should now automatically refresh the page when a user encounters a bundle error.

DEVPROD-15374 Add logic to refresh on old bundle errors

---

apps/spruce/src/components/styles/Layout.tsx
apps/spruce/src/constants/featureFlags.ts
apps/spruce/src/pages/Task.tsx
apps/spruce/src/pages/task/TaskTabs.tsx
apps/spruce/src/pages/task/taskTabs/Logs.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/TaskTimeline/__snapshots__/TaskTimeline_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/TaskTimeline/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/index.tsx

DEVPROD-16173
I intend to merge this PR following the pagination PR (evergreen-ci/ui/pull/754).
I removed the task box link because according to the designs, it doesn't work like that. The task link can still be found in the commit details cards. Depending on what the focus group users say we can rework this functionality later.

DEVPROD-16173: Unhide Task History tab on production

---

apps/spruce/src/components/Banners/ProjectBanner.tsx
apps/spruce/src/pages/waterfall/index.tsx

DEVPROD-17079
While working on deprecating the mainline commits page and all its associated tests I realized we weren't showing the project banner on the new waterfall page. This PR adds it back

DEVPROD-17079 Make project banners show up on waterfall

---

apps/spruce/cypress/integration/waterfall/navigation.ts
apps/spruce/src/analytics/waterfall/useWaterfallAnalytics.ts
apps/spruce/src/components/Content/index.tsx
apps/spruce/src/components/Redirects/WaterfallCommitsRedirect.tsx
apps/spruce/src/constants/routes.test.ts
apps/spruce/src/constants/routes.ts
apps/spruce/src/pages/waterfall/WaterfallFilters.tsx

DEVPROD-17568
Introduce a temporary redirect to redirect links from external facing apps to the new waterfall. While deprecating the page I came to the realization that we still have external apps we do not own sending traffic to the project health page. This  introduces a temporary redirect to preserve links while we identify those apps and make the necessary updates.
=

DEVPROD-17568 Redirect legacy commits page to waterfall page

---

apps/spruce/src/components/SpruceForm/Widgets/LeafyGreenWidgets.tsx
apps/spruce/src/pages/distroSettings/tabs/GeneralTab/GeneralTab.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_WithFilterApplied.storyshot

DEVPROD-16652
The 0 in the form was caused by `warnings?.length && (component)` evaluating to false.
Doesn't show a 0 anymore

DEVPROD-16652 Correctly conditionally render warning banner in spruce form

---

apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_WithFilterApplied.storyshot
apps/spruce/src/pages/task/taskTabs/buildBaronAndAnnotations/BuildBaron.tsx
apps/spruce/src/pages/task/taskTabs/buildBaronAndAnnotations/FileTicketButton.tsx

DEVPROD-4167
We weren't refreshing or polling build baron created jira tickets this adds support for that.
https://github.com/user-attachments/assets/eafe4a32-3dbc-4a5e-9ffa-b99964307ca2

DEVPROD-4167 Start auto refreshing created build baron tickets

---

apps/parsley/src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/__snapshots__/FilterGroup_Default.storyshot
apps/parsley/src/components/SidePanel/__snapshots__/SidePanel_Default.storyshot
apps/spruce/cypress/integration/task/task_history.ts
apps/spruce/src/analytics/index.ts
apps/spruce/src/analytics/task/useTaskHistoryAnalytics.ts
apps/spruce/src/analytics/types.ts
apps/spruce/src/components/HistoryTable/HistoryTableRow/BaseRow/FoldedCommit/__snapshots__/FoldedCommit_FoldedCommitStory.storyshot
apps/spruce/src/pages/host/HostEventString/__snapshots__/HostEventString_Default.storyshot
apps/spruce/src/pages/host/HostTable/__snapshots__/HostTable_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/CommitDetailsCard.stories.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/FailedTestsTable.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_WithFailingTests.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_WithFilterApplied.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/testData.ts
apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/__snapshots__/FailedTestGroup_Default.storyshot
apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/__snapshots__/FailedTestGroup_LongTestName.storyshot
packages/lib/src/components/Accordion/__snapshots__/Accordion_Default.storyshot
packages/lib/src/components/Accordion/__snapshots__/Accordion_WithSubtitle.storyshot
packages/lib/src/components/Accordion/__snapshots__/Accordion_WithToggledTitle.storyshot
packages/lib/src/components/Accordion/index.tsx

DEVPROD-16172
Adds test failure table to commit details card. Also, I messed up some `Accordion` styles so I fixed them.
Search failures and follow-up improvements will be made in [DEVPROD-16189](https://jira.mongodb.org/browse/DEVPROD-16189).
* Cypress test
* Update stories

DEVPROD-16172: Add test failure table to commit details card

---

apps/parsley/src/gql/generated/types.ts
apps/spruce/cypress/integration/task/task_history.ts
apps/spruce/package.json
apps/spruce/src/analytics/task/useTaskHistoryAnalytics.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/FailedTestsTable.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_WithFailingTests.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_WithFilterApplied.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/TestFailureSearchInput/index.tsx
packages/lib/src/components/styles/globalStyles.ts
yarn.lock

DEVPROD-16189
Adds support for searching for failures via table.
https://github.com/user-attachments/assets/ad3598f4-a158-466e-877d-58b7f1747d69
* Added Cypress tests

DEVPROD-16189: Add Search Failure button to failed tests table

---

apps/spruce/src/analytics/task/useAnnotationAnalytics.ts
apps/spruce/src/analytics/task/useTaskAnalytics.ts

DEVPROD-17617
Add some more information about the task annotation analytic events are associated with.

DEVPROD-17617 Track additional task metadata for annotation analytics

---

apps/spruce/cypress/integration/task/task_history.ts
apps/spruce/src/analytics/task/useTaskHistoryAnalytics.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/task-history.graphql
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/CommitDetailsCard.stories.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/CommitDetailsCard.test.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_WithFailingTests.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_WithLongMessage.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_WithFilterApplied.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/InactiveCommitsButton/InactiveCommitsButton.test.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/InactiveCommitsButton/__snapshots__/InactiveCommitsButton_Default.storyshot
apps/spruce/src/pages/task/taskTabs/TaskHistory/InactiveCommitsButton/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/testData.ts

DEVPROD-17610
Shows schedule button for inactive tasks.
https://github.com/user-attachments/assets/2070136c-1d10-4833-8688-059c27414f14
* e2e test

DEVPROD-17610: Show schedule button for inactive tasks on Task History

---

.evergreen/scripts/constants.js
.evergreen/scripts/generate-parallel-e2e-tasks.js
.evergreen/scripts/generate-tasks.js
.evergreen/scripts/git-utils.js
apps/parsley/src/gql/generated/types.ts
apps/spruce/src/gql/generated/types.ts

DEVPROD-11739
This PR optimizes our CI pipeline by making E2E tests conditional on relevant code changes. It introduces a check that only runs E2E tests when there are modifications in either the app-specific directory or the shared packages directory.
- Created a new `git-utils.js` module to centralize git-related functionality:
- `getMergeBase()`: Gets the merge base between current branch and main
- `whatChanged()`: Returns list of modified files in current PR/patch
- `hasChangesInDirectory()`: Utility to check for changes in specific directories
- Modified `generate-parallel-e2e-tasks.js` to:
- Check for changes in the relevant app directory (e.g., `apps/spruce`) or shared packages
- Skip E2E task generation if no relevant changes are detected
- Verified that E2E tasks are generated …

DEVPROD-11739 Only run parallel e2e tasks if we have changes in the spruce directory or the lib directory

---

apps/spruce/cypress/integration/task/task_history.ts
apps/spruce/src/analytics/task/useTaskHistoryAnalytics.ts
apps/spruce/src/constants/cookies.ts
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/DateSeparator/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/Controls/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/InactiveCommitsButton/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/TaskTimeline/DateSeparator/DateSeparator.test.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/TaskTimeline/DateSeparator/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/context/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/index.tsx
apps/spruce/src/pages/task/taskTabs/TaskHistory/utils/index.ts

DEVPROD-18287
Dziana gave the following feedback:
* Currently, in collapsed view, when you schedule an inactive task in the middle of a group, the entire group gets collapsed. Sometimes I want to schedule multiple tasks in the group so this is very awkward.
This PR attempts to address this feedback.
Before (opened sections get closed and must be reopened):
https://github.com/user-attachments/assets/7430cd3c-2d7c-4cc6-9e55-74f8243b9b7d
After (opened sections stay open):
https://github.com/user-attachments/assets/94772ac9-8cc3-4cc9-a0b0-3243007d11f1
- Added e2e test

DEVPROD-18287: Improve interaction of scheduling inactive tasks

---

apps/parsley/package.json
apps/parsley/src/utils/searchLogs/index.ts
apps/parsley/src/utils/searchLogs/searchLogs.test.ts

DEVPROD-822
Strip ANSI formatting during search so that matches with formatting can be identified.
Add unit test

DEVPROD-822: Include ANSI results in search

---

apps/spruce/src/analytics/task/useAnnotationAnalytics.ts
apps/spruce/src/analytics/task/useTaskAnalytics.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/mocks/taskData.ts
apps/spruce/src/gql/queries/index.ts
apps/spruce/src/gql/queries/task-test-count.graphql
apps/spruce/src/gql/queries/task.graphql
apps/spruce/src/pages/task/taskTabs/index.tsx

DEVPROD-18676
Remove dependency on cedar fields

DEVPROD-18676 Ensure task page does not rely on cedar fields

---

apps/spruce/cypress/integration/distroSettings/provider_section.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/pages/distroSettings/tabs/ProviderTab/schemaFields.ts
apps/spruce/src/pages/distroSettings/tabs/ProviderTab/styles.ts
apps/spruce/src/pages/distroSettings/tabs/ProviderTab/transformerUtils.ts
apps/spruce/src/pages/distroSettings/tabs/ProviderTab/transformers.test.ts
apps/spruce/src/pages/distroSettings/tabs/ProviderTab/types.ts

DEVPROD-17219
Remove fleet options from the the distro UI; we should only have on-demand for this.
Screenshot is kind of lame since I removed something haha, but it looks normal, and i was able to save without issues.
Removed from tests; I think this doesn't have to update the analytics table.
https://github.com/evergreen-ci/evergreen/pull/9223

DEVPROD-17219 remove spot fleet options from distro UI

---

apps/spruce/src/components/Spawn/spawnHostModal/getFormSchema.tsx
apps/spruce/src/components/Spawn/spawnHostModal/useLoadFormSchemaData.ts
apps/spruce/src/gql/generated/types.ts
apps/spruce/src/gql/queries/distros.graphql
apps/spruce/src/pages/distroSettings/DistroSelect/DistroSelect.test.tsx
apps/spruce/src/pages/spawn/spawnHost/spawnHostButton/SpawnHostModal.tsx

DEVPROD-15817
Instead of showing all AWS regions we support, only show the regions that each distro supports.

DEVPROD-15817: Only show available regions in spawn host modal

---

apps/spruce/src/constants/triggers.ts

DEVPROD-17659
This adds the merge queue subscriber type. I tested this on the app side, by manually setting the subscriber values to the merge queue, and it worked as expected. This just needs to be added to the UI.
The UI:
After doing it, the DB:
Deployed to spruce staging, changed the subscription type back and forth. Ran a MQ and it emailed me:
NA

DEVPROD-17659 Add merge queue subscriber type

---

apps/parsley/src/utils/prettyPrint/index.ts
apps/parsley/src/utils/prettyPrint/prettyPrint.test.ts

DEVPROD-18889
Preserve escaped quotes in key names when pretty printing resmoke logs. I used the regex introduced here: https://github.com/evergreen-ci/parsley/pull/145
Before:
After:
Add unit test

DEVPROD-18889: Preserve escaped quotes when pretty printing

---

apps/spruce/src/constants/routes.test.ts
apps/spruce/src/constants/routes.ts

DEVPROD-21399
Adds some url encoding for variant names
Unit tests

DEVPROD-21399 Encode build variant when generating variant history urls

---

apps/parsley/.env-cmdrc.json

DEVPROD-21432
If a user is on Parsley beta using AI, any links to Spruce should direct to the prod website. Since this is a temporary setup I think the easiest approach is to just change the hardcoded env var.

DEVPROD-21432 followup: Link users to spruce prod from parsley beta

---

apps/spruce/src/components/SpruceForm/SpruceForm.stories.tsx
apps/spruce/src/components/SpruceForm/SpruceForm.test.tsx
apps/spruce/src/components/SpruceForm/Widgets/DateTimePicker.tsx
apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm_DateTimePicker.storyshot
apps/spruce/src/components/TimePicker/TimeInput.tsx
apps/spruce/src/components/TimePicker/__snapshots__/TimePicker_Default.storyshot

DEVPROD-22098
Fix bug where LG's DatePicker was setting time to midnight, overriding user-specified time
This facilitates fixing DEVPROD-20523
- Add tests that fail without changes
- SpruceForm story

DEVPROD-22098: Fix date overwriting time in datetime widget
