apps/parsley/src/components/DetailsMenu/DetailsMenuCard/index.tsx
DEVPROD-5277
I forgot to unhide the toggle on the production environment 😭
=> DEVPROD-5277: Unhide jump to failing line toggle on production

apps/spruce/src/components/SpruceForm/__snapshots__/SpruceForm.stories.storyshot
DEVPROD-1128
Accidentally button mashed #61 and merged without waiting for tests to pass.
=> DEVPROD-1128 Bump snapshots for DEVPROD-1128

apps/spruce/src/pages/projectSettings/tabs/NotificationsTab/getFormSchema.tsx, yarn.lock
DEVPROD-5830
- Remove incorrect "Performance Plugin" title on notifications settings page
=> DEVPROD-5830: Remove incorrect page title

apps/spruce/src/components/ErrorHandling/Sentry.tsx, apps/spruce/src/components/ErrorHandling/initialize.test.ts
DEVPROD-3292
Remove replay since we never use it and it has potential performance drawbacks
=> DEVPROD-3292: Remove Sentry Replay

apps/parsley/src/constants/errors.ts
DEVPROD-6980
Remove reference to Evergreen tooling from partial download error
=> DEVPROD-6980: Edit partial download error

apps/spruce/src/pages/projectSettings/tabs/AccessTab/getFormSchema.ts
DEVPROD-4664
Clarify that users cannot see a restricted project unless they have special access permissions.
N/A
N/A
N/A
=> DEVPROD-4664: clarify restricted project description

apps/parsley/src/gql/generated/types.ts, apps/spruce/src/gql/fragments/projectSettings/plugins.graphql, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/projectSettings/CopyProjectModal.test.tsx, apps/spruce/src/pages/projectSettings/tabs/EventLogTab/EventLogTab.test.tsx, apps/spruce/src/pages/projectSettings/tabs/PluginsTab/getFormSchema.tsx, apps/spruce/src/pages/projectSettings/tabs/PluginsTab/transformers.test.ts, apps/spruce/src/pages/projectSettings/tabs/PluginsTab/transformers.ts, apps/spruce/src/pages/projectSettings/tabs/PluginsTab/types.ts, apps/spruce/src/pages/projectSettings/tabs/testData.ts, yarn.lock
DEVPROD-3003
This removes jira custom fields, an unused project setting.
Existing tests, and ran Spruce locally and confirmed the plugins tab still worked.
https://github.com/evergreen-ci/evergreen/pull/7832
=> DEVPROD-3003 Remove JIRA custom fields

apps/parsley/cypress/integration/ansiLogs/ansi_logView.ts, apps/parsley/src/analytics/preferences/usePreferencesAnalytics.ts, apps/parsley/src/components/DetailsMenu/DetailsMenuCard/Toggles/SectionsToggle/SectionsToggle.test.tsx, apps/parsley/src/components/DetailsMenu/DetailsMenuCard/Toggles/SectionsToggle/index.tsx, apps/parsley/src/components/DetailsMenu/DetailsMenuCard/Toggles/index.tsx, apps/parsley/src/components/DetailsMenu/DetailsMenuCard/index.tsx, apps/parsley/src/gql/generated/types.ts, apps/parsley/src/gql/mutations/update-parsley-settings.graphql, apps/parsley/src/gql/queries/parsley-settings.graphql, apps/parsley/src/hooks/useParsleySettings/index.ts, apps/parsley/src/test_data/parsleySettings.ts, apps/spruce/src/gql/generated/types.ts
DEVPROD-5289
This is being merged into the **parsley-sectioning** branch. It was already merged in Parsley repo, it needs to be added to this repo.
* <s>Will fix AWS errors by talking to DevProd Infra.</s> fixed
=> DEVPROD-5289: Add user preference toggle for sections

apps/spruce/cypress/integration/distroSettings/general_section.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/distroSettings/tabs/GeneralTab/getFormSchema.ts
DEVPROD-6656 
Unhide warnings, as mentioned in the ticket comment
=> DEVPROD-6656 unhide distro warnings field

apps/spruce/src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
DEVPROD-5915
This detail is in the docs, but also adding it to the help text here to reduce the chance of it getting missed.
=> DEVPROD-5915 Add more text to version control button

apps/spruce/cypress/integration/hosts/hosts_sorting.ts, apps/spruce/cypress/integration/spawn/host.ts
DEVPROD-7046
- Fix Cypress tests broken by https://github.com/evergreen-ci/evergreen/pull/7928
=> DEVPROD-7046: Fix e2e tests

apps/spruce/src/components/Header/Navbar.tsx, apps/spruce/src/components/Icon/icons/PrideTree.tsx
DEVPROD-7929
https://github.com/evergreen-ci/ui/assets/47064971/1f4ed28f-bea4-432c-8396-1c74e68636d0
=> DEVPROD-7929: Update Evergreen logo for Pride Month

apps/spruce/cypress/integration/container/container_events.ts, apps/spruce/cypress/integration/host/host_events.ts, apps/spruce/src/pages/preferences/preferencesTabs/NotificationsTab.tsx, apps/spruce/src/pages/preferences/preferencesTabs/ProfileTab.tsx
DEVPROD-8096
Changed button text on Preferences Profile and Notification pages.
=> DEVPROD-8096 Change button text on Preferences Profile and Notification pages

apps/spruce/src/analytics/activity/useActivityAnalytics.ts, apps/spruce/src/analytics/index.ts, apps/spruce/src/components/Header/index.tsx, apps/spruce/src/hooks/useNetworkStatus.ts, apps/spruce/src/hooks/usePageVisibility.ts
DEVPROD-8345
Remove the analytics events for tab activity
=> DEVPROD-8345 Remove tab active/not active events

apps/parsley/src/analytics/logWindow/useLogWindowAnalytics.ts, apps/parsley/src/components/LogRow/CaretToggle/index.tsx, apps/parsley/src/components/LogRow/SectionHeader/SectionHeader.test.tsx, apps/parsley/src/components/LogRow/SectionHeader/__snapshots__/SectionHeader_SectionHeaderSingle.storyshot, apps/parsley/src/components/LogRow/SectionHeader/index.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/SubsectionHeader.stories.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/SubsectionHeader.test.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/__snapshots__/SubsectionHeader_SubsectionHeaderSingle.storyshot, apps/parsley/src/components/LogRow/SubsectionHeader/index.tsx, apps/parsley/src/gql/generated/types.ts, apps/spruce/src/gql/generated/types.ts
DEVPROD-8343
This component will be used to indicate command subsections. These code changes don't actually render SubsectionHeader in the log pane. That will be completed in DEVPROD-8343
=> DEVPROD-8343: Introduce SubsectionHeader component

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/task/metadata/index.tsx
DEVPROD-6860
Annotations permissions update will result in partial errors this component.
=> DEVPROD-6860: Update Task Metadata Panel partial error state

apps/parsley/src/components/ErrorHandling/Sentry.tsx, apps/parsley/src/components/ErrorHandling/initialize.test.ts, apps/parsley/src/gql/generated/types.ts, apps/spruce/src/components/ErrorHandling/Sentry.tsx, apps/spruce/src/components/ErrorHandling/initialize.test.ts
DEVPROD-8620
Sometimes urls get cut off when we receive sentry errors this value doubles the default max length for reported sentry errors
Documentation
https://docs.sentry.io/platforms/javascript/configuration/options/#max-value-length
=> DEVPROD-8620 Update sentry config to send larger values

apps/parsley/src/components/LogRow/BaseRow/SharingMenu/utils.test.ts, apps/parsley/src/components/LogRow/RowRenderer/index.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/SubsectionHeader.stories.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/SubsectionHeader.test.tsx, apps/parsley/src/components/LogRow/SubsectionHeader/__snapshots__/SubsectionHeader_SubsectionHeaderSingle.storyshot, apps/parsley/src/components/LogRow/SubsectionHeader/index.tsx, apps/parsley/src/hooks/useSections/useSections.test.tsx, apps/parsley/src/hooks/useSections/utils.test.ts, apps/parsley/src/hooks/useSections/utils.ts, apps/parsley/src/types/logs.ts, apps/parsley/src/utils/filterLogs/filterLogs.test.ts, apps/parsley/src/utils/findLineIndex/findLineIndex.test.ts
DEVPROD-8683
Parse and render the step information for a command.
=> DEVPROD-8683: Parse and display step for command section

apps/parsley/package.json, apps/parsley/src/gql/generated/types.ts, apps/spruce/package.json, apps/spruce/src/gql/generated/types.ts, yarn.lock
DEVPROD-9361
Upgrade checkbox so that disabled checkboxes are not clickable (as per [LG-4411](https://jira.mongodb.org/browse/LG-4411))
=> DEVPROD-9361: Upgrade checkbox

apps/spruce/README.md
DEVPROD-799
Update the instructions for generating data for a feature
=> DEVPROD-799 Update readme with instructions on how to generate data for a feature

apps/parsley/src/hooks/useOpenSectionAndScrollToLine/index.ts, apps/parsley/src/hooks/useOpenSectionAndScrollToLine/useOpenSectionAndScrollToLine.test.ts, apps/spruce/src/pages/version/taskDuration/TaskDurationTable.tsx, apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_Default.storyshot, apps/spruce/src/pages/version/taskDuration/__snapshots__/TaskDurationTable_LongContent.storyshot
Reverts evergreen-ci/ui#273
The project build was broken by the commit.
=> Revert "DEVPROD-6448: Update task duration links to route to latest execution"

.github/pull_request_template.md, README.md, apps/spruce/src/components/styles/Layout.tsx, apps/spruce/src/pages/configurePatch/configurePatchCore/__snapshots__/ConfigurePatchCore_ConfigureTasksDefault.storyshot
Reverts evergreen-ci/ui#312
caused see log buttons to disappear
=> Revert "DEVPROD-1065: Remove antd layout"

apps/spruce/cypress/integration/host/host_events.ts, apps/spruce/src/pages/host/HostEventString.tsx, apps/spruce/src/types/host.ts
DEVPROD-7687
Add host temporary exemption expiration warning sent.
Added to existing Cypress test. 
https://jira.mongodb.org/browse/DEVPROD-4183
=> DEVPROD-7687: Add host temporary exemption expiration warning sent

apps/spruce/src/constants/externalResources.ts, apps/spruce/src/constants/featureFlags.ts, apps/spruce/src/pages/projectSettings/Tabs.tsx, apps/spruce/src/pages/projectSettings/index.tsx
DEVPROD-8967
This release the UI to production by removing the use of the feature flag. This also, update the documentation URL for the app settings tab.
This will be merged alongside these three evergreen doc prs: 
[part one](https://github.com/evergreen-ci/evergreen/pull/8198)
[part two](https://github.com/evergreen-ci/evergreen/pull/8208)
[part three](https://github.com/evergreen-ci/evergreen/pull/8209)
=> DEVPROD-8967 Remove feature flag and update documentation URL

apps/spruce/src/components/Content/index.tsx, apps/spruce/src/components/Redirects/PatchRedirect.tsx, apps/spruce/src/components/Redirects/index.ts, apps/spruce/src/constants/routes.ts
DEVPROD-5907
Add redirect when user visits `/patch/<patchID>` to `/version/<versionID>`
=> DEVPROD-5907: Redirect from patch route to version route

apps/parsley/src/components/DetailsMenu/DetailsMenuCard/index.tsx, apps/parsley/src/context/SectionsFeatureDiscoveryContext/JumpToFailingLineToggleGuideCue.tsx, apps/parsley/src/context/SectionsFeatureDiscoveryContext/SectionsFeatureModal/index.tsx, apps/parsley/src/context/SectionsFeatureDiscoveryContext/SectionsToggleGuideCue.tsx, apps/parsley/src/hooks/useSections/index.ts, apps/parsley/src/utils/featureFlag/index.ts
DEVPROD-9665
This PR won't be merged until the introduction email is approved by the team.
=> DEVPROD-9665: Release sectioning beta

apps/parsley/src/context/SectionsFeatureDiscoveryContext/SectionsToggleGuideCue.tsx, apps/parsley/src/gql/generated/types.ts
DEVPROD-11251
The bug is visible in the prod build and maybe visible locally if you really clear out your npm modules. I put a delay on the tooltip to wait for the details menu transition. I tested this beta by deploying from Evergreen (deploying locally hid the bug for me).
=> DEVPROD-11251: Fix jumpy first guidcue during sectioning discovery flow

packages/lib/src/utils/observability/honeycomb.ts
=> DEVPROD-11309 Fix conditional check for Honeycomb INGEST API key and collector endpoint

ANALYTICS.md
DEVPROD-9937
Updates the analytics README with information on how to query Honeycomb.
=> DEVPROD-9937 Update analytics documentation with info on querying

apps/spruce/src/components/Header/Navbar.tsx, apps/spruce/src/components/Icon/AnimatedIcon/AnimatedIcon.test.tsx, apps/spruce/src/components/Icon/AnimatedIcon/index.tsx, apps/spruce/src/components/Icon/icons/FallTree.tsx
=> DEVPROD-11911 Add pause back to the spruce logo animation.

.evergreen/evergreen.yml
DEVPROD-11699
Bump MongoDB to 8.0 to match prod
=> DEVPROD-11699 Bump MongoDB to 8.0

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/waterfall.graphql, apps/spruce/src/pages/waterfall/BuildRow.tsx
DEVPROD-11734
Fetch task execution number for each task to use in waterfall link
https://github.com/evergreen-ci/evergreen/pull/8424
=> DEVPROD-11734: Use task execution in waterfall links

apps/parsley/src/gql/generated/types.ts, apps/spruce/src/components/Spawn/spawnHostModal/getFormSchema.tsx, apps/spruce/src/gql/generated/types.ts
DEVPROD-5268
Adds a disclaimer for where task files will be when spawning a host from a task
=> DEVPROD-5268 Add disclaimer for file locations when spawning hosts

apps/spruce/src/components/Content/index.tsx, apps/spruce/src/constants/featureFlags.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/distroSettings/index.tsx, apps/spruce/src/pages/distroSettings/tabs/GeneralTab/getFormSchema.ts, apps/spruce/src/pages/task/metadata/ImageVisibilityGuideCue.tsx, apps/spruce/src/pages/task/metadata/index.tsx
DEVPROD-11433
Releases the project to production.
=> DEVPROD-11433: Release Image Visibility page

apps/parsley/cypress/integration/uploadedLogs/upload.ts, apps/parsley/cypress/support/commands.ts, apps/parsley/cypress/support/index.ts, apps/parsley/src/analytics/logDrop/useLogDropAnalytics.ts, apps/parsley/src/gql/generated/types.ts, apps/parsley/src/hooks/useClipboardPaste/index.ts, apps/parsley/src/hooks/useClipboardPaste/useClipboardPaste.test.ts, apps/parsley/src/pages/LogDrop/FileDropper.tsx, apps/parsley/src/pages/LogDrop/FileSelector/index.tsx, apps/parsley/src/pages/LogDrop/constants.ts, apps/parsley/src/pages/LogDrop/state.ts, apps/spruce/src/gql/generated/types.ts
DEVPROD-803
Adds support to copy and paste files into Parsley from the upload page.
Went against the approach of including a text box because the UX didn't work and pasting a large file into a text box causes the browser to freeze up.
=> DEVPROD-803 Support uploading files to Parsley via clipboard [minor]

.github/pull_request_template.md
=> DEVPROD-11627: Update PR template with versioning guideline link

apps/parsley/src/context/LogContext/state.ts, apps/parsley/src/gql/generated/types.ts
DEVPROD-8728
Unset the failingLine value if we can't find a match for failing logs
=> DEVPROD-8728 Ensure failing line index doesn't show up as -1

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/task/metadata/index.tsx
DEVPROD-9506
Update warning message when clicking the reset when finished functionality to not reference task groups.
=> DEVPROD-9506 Update reset-when-finished warning message

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/projectSettings/tabs/PluginsTab/getFormSchema.tsx
DEVPROD-13114
Fixed the description field of the perf plugin section to fix a broken boolean
=> DEVPROD-13114 Fix boolean logic in perf plugin description

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/host/HostEventString/HostEventString.stories.tsx, apps/spruce/src/pages/host/HostEventString/__snapshots__/HostEventString_Default.storyshot, apps/spruce/src/pages/host/HostEventString/index.tsx, apps/spruce/src/pages/host/HostTable/HostTable.stories.tsx, apps/spruce/src/pages/host/HostTable/__snapshots__/HostTable_Default.storyshot, apps/spruce/src/pages/host/HostTable/index.tsx, apps/spruce/src/pages/host/index.tsx
DEVPROD-13476
Create new event type for spawn host creation failure as well populate some other missing event types I found. Also created storybook stories so its easier to spot these in the future. 
I promise this pr isn't super big the large diff is just snapshots
https://github.com/evergreen-ci/evergreen/pull/8557
=> DEVPROD-13476 Create spawn host failing to create event type

apps/spruce/cypress/integration/spawn/host.ts
DEVPROD-13917
These tests started failing on the main branch and every branch. I can't really gather as to why they started failing today (Maybe something due to do with 2025?) but it seems related to some faulty date selection logic.
Tested it locally and ensured dates are selected reliably.
=> DEVPROD-13917 Fix bug with date selection logic in spawn host tests

apps/spruce/cypress/integration/waterfall/filters.ts, apps/spruce/cypress/support/commands.ts, apps/spruce/cypress/support/e2e.ts, apps/spruce/src/pages/waterfall/DateFilter/index.tsx, apps/spruce/src/pages/waterfall/InactiveVersions/InactiveVersionsModal.tsx, apps/spruce/src/pages/waterfall/InactiveVersions/index.tsx, apps/spruce/src/pages/waterfall/WaterfallGrid.tsx
DEVPROD-14252
- When navigating to a date, show blue highlight to indicate the operation has completed
- Clear date picker date on page navigation
- Done by making Waterfall date picker controlled component; since we're no longer using a transition this is a more predictable way to control the component
- Ensure that highlight applied on navigation and date input cleared on pagination.
- Created a helper function to validate LeafyGreen Date Picker inputs.
=> DEVPROD-14252: Polish waterfall date picker interactions

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/waterfall.graphql
DEVPROD-14608
#607 forgot to remove the `UpstreamProject` fragment from the waterfall query
=> DEVPROD-14608: Remove upstream from waterfall query

apps/spruce/src/pages/projectSettings/tabs/GithubCommitQueueTab/getFormSchema.tsx
DEVPROD-14357
###Description
Added some words to better describe the behavior of github features when enabled from the repo. Added screenshots below.
=> DEVPROD-14357 add more descriptions to project page

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/waterfall/DateFilter/index.tsx
DEVPROD-14759
The date picker will now prevent date selection before 1 year ago.
=> DEVPROD-14759: Disable waterfall datepicker before 1 year

apps/spruce/src/pages/version/Tabs/DownstreamTasks/DownstreamProjectAccordion.tsx
DEVPROD-14587
Remove onError handler since this is a common and expected state.
=> DEVPROD-14587: Remove error toast for missing downstream tasks

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/__snapshots__/FailedTestGroup_Default.storyshot, apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/__snapshots__/FailedTestGroup_LongTestName.storyshot, apps/spruce/src/pages/version/Tabs/TestAnalysis/GroupedTestMapList/FailedTestGroup/index.tsx
DEVPROD-14937
Remove trimming logic
=> DEVPROD-14937 Don't trim long test names on test analysis tab

apps/spruce/src/components/MetadataCard.tsx, apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_ContainerizedTask.storyshot, apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_Default.storyshot, apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_OOMTracker.storyshot, apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithAbortMessage.storyshot, apps/spruce/src/pages/task/metadata/__snapshots__/Metadata_WithDependencies.storyshot, apps/spruce/src/pages/version/BuildVariantCard/__snapshots__/BuildVariantCard_Default.storyshot, apps/spruce/src/pages/version/Metadata.tsx, apps/spruce/src/pages/version/ParametersModal/__snapshots__/ParametersModal_Default.storyshot
DEVPROD-11546
These are 2 of the most common questions we get on Evergreen. This adds info sprinkles to explain what these fields mean.
=> DEVPROD-11546 Add info sprinkle to makespan and time taken fields

.evergreen/scripts/constants.js, .evergreen/scripts/generate-tasks.js
DEVPROD-9881
Ignore markdown files in Evergreen task generator
=> DEVPROD-9881: Ignore markdown files in task generator

apps/parsley/cypress.config.ts, apps/spruce/cypress.config.ts
DEVPROD-9841
After each run, delete the video if no tests failed.
=> DEVPROD-9841: Don't upload passing Cypress videos

apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/user-subscriptions.graphql, apps/spruce/src/pages/preferences/preferencesTabs/notificationTab/useSubscriptionData.tsx
DEVPROD-13093
Forgot to remove `userSettings` query from one last place.
=> DEVPROD-13093: Remove userSettings query from subscriptions

apps/spruce/src/pages/projectSettings/tabs/GeneralTab/getFormSchema.tsx
DEVPROD-9352
Removes 'Force Repotracker Run' button on repos.
=> DEVPROD-9352: Remove "Force Repotracker Run" button from repo settings page

apps/spruce/cypress/integration/waterfall/filters.ts, apps/spruce/src/gql/client/cache.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/waterfall/WaterfallGrid.tsx
DEVPROD-10179
Use server side filtering when `n < limit` versions are present on the page when a task name or status filter is applied.
Update e2e tests -- test data is fixed in Evergreen PR
https://github.com/evergreen-ci/evergreen/pull/8830
=> DEVPROD-10179: Add task name and status filtering

apps/parsley/src/gql/generated/types.ts, apps/spruce/cypress/integration/distroSettings/single_task_distro.ts, apps/spruce/src/components/Settings/Context.tsx, apps/spruce/src/constants/routes.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/index.ts, apps/spruce/src/gql/queries/single-task-distro.graphql, apps/spruce/src/pages/distroSettings/Tabs.tsx, apps/spruce/src/pages/distroSettings/getTabTitle.ts, apps/spruce/src/pages/distroSettings/index.tsx, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/SingleTaskDistroTab.tsx, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/getFormSchema.ts, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/transformers.test.ts, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/transformers.ts, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/types.ts, apps/spruce/src/pages/distroSettings/tabs/types.ts
DEVPROD-15349
e2e tests depend on https://github.com/evergreen-ci/evergreen/pull/8827
=> DEVPROD-15349: Render Single Task Distro Settings Page

.optibot
Prevent optibot from auto commenting on prs without first being asked.
=> Disable auto reviews from optibot

apps/spruce/cypress/integration/distroSettings/single_task_distro.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/single-task-distro.graphql, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/getFormSchema.ts, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/transformers.test.ts, apps/spruce/src/pages/distroSettings/tabs/SingleTaskDistroTab/transformers.ts
DEVPROD-16104
Depends on https://github.com/evergreen-ci/evergreen/pull/8876
=> DEVPROD-16104: Render allowed build variants in Distro Settings Page

apps/parsley/README.md, apps/spruce/README.md
DEVPROD-NNNNN
Just updating the docs
=> [DOCS] Update Node.js version requirement to v22+ in README files

apps/spruce/cypress/integration/task/task_history.ts, apps/spruce/src/components/DateFilter/index.tsx, apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/__snapshots__/CommitDetailsCard_Default.storyshot, apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsCard/index.tsx, apps/spruce/src/pages/task/taskTabs/TaskHistory/CommitDetailsList/__snapshots__/CommitDetailsList_Default.storyshot, apps/spruce/src/pages/task/taskTabs/TaskHistory/Controls/index.tsx
DEVPROD-16621
Add button for jumping to task.
https://github.com/user-attachments/assets/3e6933fc-153a-4bdc-b50a-584663fd6da2
* Added Cypress tests
=> DEVPROD-16621: Implement "Jump to this task" button for Task History

.github/dependabot.yml
DEVPROD-17458
Rely on the codeowners file instead.
=> DEVPROD-17458 Remove reviewers field from dependabot config

.evergreen/evergreen.yml, .evergreen/pine.yml
DEVPROD-9156
Adds the downstream pine task for the Evergreen ui project
=> DEVPROD-9156 Add pine downstream task to Evergreen UI

apps/parsley/src/gql/generated/types.ts, apps/parsley/src/hooks/useFilterParam/index.ts
=> DEVPROD-8705 Memoize useFilterParam results

apps/spruce/src/analytics/version/useVersionAnalytics.ts, apps/spruce/src/pages/version/Tabs/TestAnalysis/index.tsx
DEVPROD-18919
Capture some additional analytics on the test analysis tab 
Yes i've updated analytics doc
=> DEVPROD-18919 Capture test analysis tab stats

apps/parsley/src/gql/generated/types.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/mutations/save-admin-settings.graphql, apps/spruce/src/gql/queries/admin-settings.graphql, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/FeatureFlagsTab/formSchema.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/FeatureFlagsTab/transformers.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/FeatureFlagsTab/types.ts
DEVPROD-17214
This was deleted in the backend pr but was not deleted here
=> DEVPROD-17214 Remove deleted BackgroundCleanupDisabled feature flags

apps/spruce/src/components/Spawn/editHostModal/getFormSchema.tsx
=> DEVPROD-18958 use password input type for rdp password

apps/spruce/cypress/integration/adminSettings/authentication.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/admin-settings.graphql, apps/spruce/src/pages/adminSettings/index.tsx, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/AuthenticationTab.tsx, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/getFormSchema.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/schemaFields.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/transformers.test.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/transformers.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/AuthenticationTab/types.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/GeneralTab.tsx
[DEVPROD-19031](https://jira.mongodb.org/browse/DEVPROD-19031)
Add authentication forms to admin settings
local testing
=> DEVPROD-19031: add authentication forms to admin settings

apps/spruce/src/components/Spawn/getFormSchema.tsx, apps/spruce/src/components/Spawn/utils/hostUptime.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/projectAndRepoSettings/shared/tabs/PeriodicBuildsTab/getFormSchema.ts
DEVPROD-19611 
The date inputs seem to default to midnight so we should have the disabled state be the same so that we don't prevent people from setting the same day as a disabled date option.
Before:
After:
=> DEVPROD-19611 Update date handling in form schemas to reset time to midnight for date fields

apps/spruce/src/components/Settings/sharedStyles.ts, apps/spruce/src/components/styles/Layout.tsx, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/pages/adminSettings/Header.tsx, apps/spruce/src/pages/adminSettings/Tabs.tsx, apps/spruce/src/pages/adminSettings/getTabTitle.ts, apps/spruce/src/pages/adminSettings/index.tsx, apps/spruce/src/pages/projectAndRepoSettings/shared/Header.tsx
[DEVPROD-19285](https://jira.mongodb.org/browse/DEVPROD-19285)
adds sticky header with a save button
=> DEVPROD-19285: Added sticky header with save button

apps/spruce/cypress/integration/adminSettings/other.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/admin-settings.graphql, apps/spruce/src/pages/adminSettings/index.tsx, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/BackgroundProcessingTab/schemaFields.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/GeneralTab.tsx, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/OtherTab.tsx, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/getFormSchema.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/schemaFields.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/transformers.test.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/transformers.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/types.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/ProvidersTab/getFormSchema.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/ProvidersTab/schemaFields.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/ProvidersTab/transformers.test.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/ProvidersTab/transformers.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/ProvidersTab/types.ts, apps/spruce/src/pages/adminSettings/tabs/sharedStyles.ts
[DEVPROD-19040](https://jira.mongodb.org/browse/DEVPROD-19040)
backend pr https://github.com/evergreen-ci/evergreen/pull/9293 
Added the other section of the admin settings page 
local testing and cypress test
=> DEVPROD-19040: added other section to admin settings

apps/spruce/src/hooks/useLegacyUIURL/index.ts, apps/spruce/src/hooks/useLegacyUIURL/useLegacyUIURL.test.tsx
DEVPROD-18445
Removes "Switch to Legacy UI" from navbar on task page
=> DEVPROD-18445: Remove "Switch to Legacy UI" link on task pages

apps/parsley/.env-cmdrc.json, apps/parsley/src/gql/generated/types.ts, apps/spruce/src/gql/generated/types.ts, packages/fungi/src/AnimatedEllipsis.tsx, packages/fungi/src/ChatFeed/ChatFeed.test.tsx, packages/fungi/src/ChatFeed/index.tsx, packages/fungi/src/Disclaimer/Disclaimer.stories.tsx, packages/fungi/src/MessageRenderer/MessageRenderer.stories.tsx, packages/fungi/src/MessageRenderer/ToolRenderer.test.tsx, packages/fungi/src/MessageRenderer/ToolRenderer.tsx, packages/fungi/src/MessageRenderer/constants.ts, packages/fungi/src/MessageRenderer/index.tsx, packages/fungi/src/Suggestions/Suggestions.stories.tsx
DEVPROD-21481
Add banner for tool action and render markdown for message content
=> DEVPROD-21481: Add tool and markdown renderer

apps/parsley/docs/01-Home.md, apps/parsley/docs/07-Parsley-AI.md
DEVPROD-21980
Added some documentation to show up in Pine about Parsley AI
=> DEVPROD-21980 Add docs for Parsley AI

apps/spruce/src/components/Header/Navbar.tsx, packages/lib/src/components/Icon/icons/logos/FallLogo.tsx, packages/lib/src/components/Icon/index.ts
DEVPROD-22556
Updates the icon for Fall
=> DEVPROD-22556: Update Spruce logo for fall

apps/parsley/src/gql/generated/types.ts, apps/spruce/src/gql/generated/types.ts, apps/spruce/src/gql/queries/admin-settings.graphql, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/schemaFields.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/transformers.test.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/transformers.ts, apps/spruce/src/pages/adminSettings/tabs/GeneralTab/OtherTab/types.ts, packages/lib/src/gql/generated/types.ts
DEVPROD-18815
A new field has been added to the admin settings. Adding it to Spruce alongside the Evergreen PR.
Existing tests
https://github.com/evergreen-ci/evergreen/pull/9393
=> DEVPROD-18815 Introduce minimum allowed CLI version
